### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1026]
```[tasklist]
### Tasks
- [x] Upgrade dev to new designs based on size/density #1170
- [x] Move to core and general improvements
- [x] Documentation
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1212
- [x] Content review @sion-docs
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1363
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1498
```

**Comment by parsakhan21** [comment]
2/15 - in progress, paul to review

**Comment by joshwooding** [comment]
PR to be reviewed

**Comment by joshwooding** [comment]
> @joshwooding were you able to review this?

Yep
