### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by Fercas123** [jpmorganchase/salt-ds#1033]
```[tasklist]
### Avatar
- [x] Design spec provided
- [x] Design docs provided
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1130
- [x] Dev review
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1210
- [x] Design review
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1211
```

**Comment by parsakhan21** [comment]
1/25 - no progress

**Comment by joshwooding** [comment]
@Fercas123 Any updates?

**Comment by pseys** [comment]
I've completed the first draft of the Component spec, which can be reviewed here: https://www.figma.com/file/8v45pWzCsJ9NZv2m4GLMyk/Avatar?node-id=1%3A2804&t=0ymPocXYPomHGWpP-1

It needs the ADA spec adding, but my assumption is that this should be relatively quick as its a primitive component with no functionality, it is purely decorative.  

@bhoppers2008 @maj-stella @Fercas123 @el-dav

**Comment by joshwooding** [comment]
Meeting later today to talk about changes in PR,
@pseys finishing up design spec

**Comment by pseys** [comment]
- Design specs complete and reviewed by @bhoppers2008 
- Light mode Figma component created and awaiting review by @bhoppers2008 
- Once Light mode component has been QA'd I'll create the Dark mode equivalent
