### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1046]
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [ ] Interaction spec
- [ ] Accessiblity spec
- [ ] Figma component
```

```[tasklist]
### Checklist
- [x] UITK audit
- [x] Landscape - Additional opportunities Salt should consider
- [x] Scope + Kick off - Describe, and update/create issues for, logical version releases; Hold kick off meeting to align team
- [x] Characteristics - Define tokens for v1
- [ ] Interaction - Define behaviours for v1
- [ ] ADA - Define the accessible experience of v1
- [ ] Documentation - Populate template with stories and best practices
- [ ] Build & QA - (Capacity dependent) Assist as required with build and QA to spec
```

```[tasklist]
### Dev Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```

**Comment by parsakhan21** [comment]
do we have a designer assigned to this work to complete the figma component task? 
Understand ben will provide design feedback, but can someone pick up the component bit so it doesnt all fall on Ben? @bhoppers2008

**Comment by parsakhan21** [comment]
July 14 - PR approved, release date of today - ?

**Comment by parsakhan21** [comment]
July 17 - dev complete; docs need to be reviewed by content; no design work done (designs pending)

**Comment by shinytoyrobots** [comment]
When is the design input scheduled? When is the content review scheduled?

**Comment by bhoppers2008** [comment]
@joshwooding @parsakhan21 Accordion spec is [here](https://www.figma.com/file/plKbS0xReVRMQ3eksSkaJs/Accordion?type=design&node-id=1626%3A280233&mode=design&t=AnH4wUvRungI86Qd-1).

**Comment by AnniaT** [comment]
@bhoppers2008 to review the build. Once reviewed - ready for release

check on figma component.

**Comment by bhoppers2008** [comment]
Design review on build done. 2 items:
1. Focus looks to be moving into a closed accordion on tab key press. Can we ignore contents when closed?
2. Can focus ring be inner border, rather than outer - see example: https://www.figma.com/file/plKbS0xReVRMQ3eksSkaJs/Accordion?type=design&node-id=5537%3A579&mode=design&t=LWOvp8JiKeIEHJuR-1

@joshwooding

**Comment by parsakhan21** [comment]
@bhoppers2008 Josh is still awaiting some feedback for the docs from design pov, do you think you can get this to him before you are out this week? Thanks!

**Comment by bhoppers2008** [comment]
Figma component and guide published internally and externally.

Haven't looked at docs this week. Will pick up next week.
