### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1052]
```[tasklist]
### Features
- [ ] Icon only
- [ ] Icon with text
- [ ] Text only
- [ ] Toggleability
```

```[tasklist]
### Design tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1793
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1819
```

**Comment by ivan-calderon** [comment]
- June 7: Design specs in progress. Expect to provide initial work for review today.
