### ISSUE TITLE
Badge v1

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1056]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### V1 Features
- [ ] Numerical and alpha badge
- [ ] Max figure support, default to 4 numerical values and append '+' if exceeds. For alpha, default to 4 characters before truncation takes place
- [ ] Accent colour for V1
- [ ] Positioning to top-right of elements
- [ ] Custom colour support (eg., categorical palette) - Replaces UITK variant (can't denote status by colour alone)
- [ ] Inline positioning when not child is passed to the component
```

**Comment by joshwooding** [comment]
Moved to Amber due to Pill vs Badge conversation as well as holiday.

**Comment by navkaur76** [comment]
V2 badge considerations: 

- Standalone (terminology TBD) - alternative positioning
- Discrete dot indicator variant

**Comment by parsakhan21** [comment]
July 19- on track for design - should be complete by end of week; PR is also ready for review

**Comment by joshwooding** [comment]
21/07 - on track for Monday release, code needs to updated

**Comment by AnniaT** [comment]
Ready for labs release today/Monday

**Comment by parsakhan21** [comment]
July 31 - docs ready to be filed to MDX (James);

**Comment by james-nash** [comment]
FYI, PR for the docs conversion is up here: https://github.com/jpmorganchase/salt-ds/pull/2105

**Comment by AnniaT** [comment]
Dev currently in review @dplsek to review

Docs - PR to be reviewed

Figma - released

**Comment by parsakhan21** [comment]
August 3 - String truncation has been removed
Spacing for Icon has been changed to use the salt spacing token 100 for both vertical and horizontal alignment
 
Dev work and docs in story book have been completed and merged.
Please see here: https://9cbfb25f.saltdesignsystem-storybook.pages.dev/?path=/story/documentation-lab-badge--page
