### ISSUE TITLE
Office Hours initiative

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#1062]
- [x] Run Office Hours workshop with wider team to gain ideas and feedback
- [x] Define what Office Hours means
- [x] Agree a format
- [x] Create Confluence sign up page
- [x] Seek final feedback / sign off from team
- [x] Get together an agenda and list of volunteers for first couple of sessions
- [x] Run first session

**Comment by parsakhan21** [comment]
2/8 - Meeting today to speak about how to socialize this

**Comment by shinytoyrobots** [comment]
We should create a `go` link for internal sign-ups.

**Comment by shey-v** [comment]
Tasks to be done by Shey / James by EOD:

- Draft a slide for Robin to share at the dxd call tomorrow
- Set up a go link for internal sign ups 
- Draft an email to share with dxd tomorrow
- Draft a symphony message to be sent on symphony post dxd call tomorrow

**Comment by shey-v** [comment]
2/9 - Paul will socialise today on dxd global call. Following this James will post message in Symphony rooms with go-link to encourage sign up. 

Agenda for first session to follow. Let's aim to also socialize office hours in our next announcement email @james-nash

**Comment by james-nash** [comment]
Yup. I've just drafted an email newsletter and sent it to @rufcha for review. All going well, we should be able to send that out in the coming days.
