### ISSUE TITLE
Storybook IA

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1087]
```[tasklist]
### Tasks
- [ ] Remove pascal case of component names in titles and references
- [ ] Change order of Storybook sidebar
- [ ] Standardise All/Defaults, titles to not include component names
- [ ] Remove subnav/stories from docs section
- [ ] Match core/lab structure
- [ ] Split progress stories into subfolders
```

**Comment by parsakhan21** [comment]
2/8 - PR up for review, should finish by today
