### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1096]
```[tasklist]
### Tasks
- [x] Development
- [x] Testing
- [x] Documentation
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1360
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1118
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1321
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1493
```
Figma: https://www.figma.com/file/gbHcDLjP1M976avIlRDWl7/Card?t=KA1urnH7kky95OTC-0

**Comment by parsakhan21** [comment]
2/6 - requires design review; pr up to move to core

**Comment by libertymayc** [comment]
31/3 waiting on dev review @joshwooding

**Comment by libertymayc** [comment]
April 14 - considering ADA adjustments and awaiting reply from @maj-stella on ada ticket
