### ISSUE TITLE
Convert Salt design system site to Next.js/Mosaic

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#1101]
Following discussion today...

Our long term architectural approach for the site will be Next.js based. We will migrate away from Docusaurus.

Prior to additional site work in terms of content pages, templates, we will replicate the existing Salt site in Next.js, and use that as the foundation for further iteration.

@james-nash @JoanaMMoreira @JohannaJoergensen @shey-v fyi

```[tasklist]
### Tasks
- [x] Check-in with Mark Tate to discuss Mosaic migration
- [x] Steve King to grant Jo access to repo
- [ ] #1121 
- [x] Determine the approach towards migration - i.e. one page or lump work
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1143
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1173
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1236
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1197
- [x] Code and design reviews
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1180
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1370
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1371
- [x] Add site redirects so users can access pages without using the salt prefix e.g. https://next.saltdesignsystem.com/getting-started, https://next.saltdesignsystem.com/components, etc
```

**Comment by JohannaJoergensen** [comment]
- [ ] Check-in with Mark Tate to discuss Mosaic migration
- [ ] Steve King to grant Jo access to repo
- [ ] Install next.js/mosaic
- [ ] Determine the approach towards migration - i.e. one page or lump work
- [ ] Determine page layout and theming
- [ ] Migrating the content and styles 
- [ ] Migrating custom made/docusaurus components
- [ ] Code and design reviews

**Comment by JohannaJoergensen** [comment]
8 Feb - Jo reached out to Mark - mtg to be scheduled

**Comment by parsakhan21** [comment]
hi all, has this meeting been scheduled with Marc? @james-nash 

Can we get some preliminary estimated delivery dates around the below tasks? 

- Determine the approach towards migration - i.e. one page or lump work
- Determine page layout and theming
- Migrating the content and styles
- Migrating docusaurus components (navbar, vertical navigation, TOC, hamburger menu, footer, etc.)
- Migrating custom made components (card, link, etc)
- Code and design reviews

Thank you.

**Comment by parsakhan21** [comment]
April 6 - migrating docs
