### ISSUE TITLE
SplitLayout Dev implementation

### ISSUE THREAD

**Issue by Fercas123** [jpmorganchase/salt-ds#1127]
```[tasklist]
### Tasks
- [x] Component implemented in TypeScript
- [x] Functional test script is implemented in Cypress and passes
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
- [x] Dev docs content provided
- [x] Consolidated documentation published on Storybook
```
