### ISSUE TITLE
Salt Component Rapid Usability Test

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1149]
Evaluation of visual affordance / expectancy

```[tasklist]
### Tasks
- [x] Method & protocols
- [x] Reusable template for study
- [x] Test 2-3 released components
- [x] Report on results
```

Note Stella in loop with tests and will be giving feedback on iterating and creating method that can be expanded to accessibility (e.g. testing with visually impaired users)

**Comment by parsakhan21** [comment]
2/15 - set up study for button, will try to also do for status indicator - collecting data around this

**Comment by zdxd** [comment]
Data gathered and analysed - meeting to report on results booked for Monday 20th

**Comment by zdxd** [comment]
nothing to add - will close after review of results today

**Comment by zdxd** [comment]
Take-aways
- Users understand the Button interaction (80% thought to "click-it") however, comparison to the rates of another design system is worthwhile
- The status icons have more ambiguity in isolation than previously thought (specifically error and warning)
