### ISSUE TITLE
Primary button comparison to another design system

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1178]
```[tasklist]
### Tasks
- [x] Confirm design systems to compare to (e.g., material UI, FINASTRA, Goldman?)
- [x] Set up screeners and run test
- [x] Analyse & format results
- [x] Share w/ team
```

**Comment by JohannaJoergensen** [comment]
24 Feb - work in progress; will share results with team on Mon, 27 Feb
