### ISSUE TITLE
Community indexes (Über epic)

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1205]
In order to promote and foster a vibrant eco-system of "satellite" design systems, tools and consumers that integrate with and/or use the core Salt Design System, we want to be able to surface their components, patterns, work, tools, etc. directly in our website.

The benefits of this are:

* Increase visibility and usage of satellite DSes and tool makers, which should:
    * Help avoid redundant work, since they can discover more easily when they are making very similar things and (hopefully) decide to collaborate
    * Give us better insight into how Salt's core components, features, etc. are being used and identify potential candidates to contribute "up" into the core DS
    * Might also help in the opposite direction: If we ever want to deprecate rarely used things, we might be able to identify satellite DSes whose users have a stronger requirement for those components and would therefore be willing to take on ownership of them
* Provide all Salt consumers with a richer set of components and functionality
* Enable Salt consumers to showcase the apps they're designing and building with Salt in order to get kudos and inspire each other

At a high level, the idea is that community projects, which have their own websites, could push metadata about items they want indexed (e.g. individual components, patterns, tools, etc.) to the Salt website. This would result in links to those items (on their own sites) appearing in the relevant sections of the Salt website.

![ecosystem](https://user-images.githubusercontent.com/16718916/221577157-2a45da25-8de9-437a-a773-0ec379dbd31b.jpg)

### Requirements and considerations

* For any community-sourced items (e.g. components, tools, patterns...), we will **only display descriptive meta-data** (e.g. name, contributor, preview thumbnail, short description, etc.) **within the Salt website, but link out to the relevant page on _their_  website for the full details**.
    * For example, let's say satellite design system "Pepper" adds their "Grinder" component to our index. We might display the "Grinder" component in our list of all components, but clicking the link would take you to the "Grinder" component documentation page on the "Pepper" website.
    * The reasoning for this is as follows:
        * Their documentation style and structure does not necessarily match our own (and forcing it to, would raise the barrier to entry), so it might not "fit" into our page templates
        * If they are publishing something to consumers they will necessarily already have published corresponding docs. Duplicating that content at another URL is redundant
        * We're trying to promote _them_, so artificially keeping visitors within our website by duplicating their content contradicts that aim.
* The **barrier to getting something listed on our site should be as low as possible** (ideally self-service and automated)
    * This does however mean that the maturity, support and quality of community components may be variable and differ from our own! Hence the next requirement...
* We should **make it easy for visitors on the Salt website to differentiate between items that have come from the community and our own** "core" design system things.
     * Our content & UI design might use labels & badges to clarify an item's provenance (i.e. "this is a Pepper component" versus "this is a Salt core component")
     * We might also explore filters on index pages and search, so that visitors can choose to view "all components", "only Salt core component" and so on.
* We should **make it easy for consumers to find things that are compatible with the current version of Salt**.
    * Although we aim to minimize breaking changes, over time it's likely that there will be different major versions of Salt. We therefore need to give some thought to compatibility and versioning between the core DS and any 3rd party components, tools, etc. Perhaps community-contributed items can indicate a version range of Salt core that they're compatible with and we can filter on that?
* We should **ensure that all community indexes are up to date**.
    * We need to find ways to identify and update or prune community items that are outdated, no longer supported or even gone. Ideally with the help of automation
    * Perhaps we can regularly crawl URLs of community items to identify broken links (which we should then remove) or permanent redirects (for which we should update the URL in our index)?
    * We may want to require a contact email for all community items, so that - if in doubt - we have a means of contacting the maintainers
* We need to think about **if and how we can include JPM-internal community items in our index**.

### Tasks & sub-epics

```[tasklist]
### Tasks
- [ ] Setup mechanism(s) for adding to the community index
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1207
- [ ] Community index for patterns
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1208
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1209
- [ ] Community index for themes
```

**Comment by shinytoyrobots** [comment]
I think we are on the same kind of line of thinking.

I agree that the showcase moves well beyond shared components (that's step 1). Much more additional value when we start making patterns available also. Theming and tooling both make sense as additional catalog items. 

I've put together some thoughts [in Figma](https://www.figma.com/file/OwL28CXhlerBLZGOnAbCJ9/Salt-ecosystem-(concepts)?node-id=223%3A307&t=nZCOnR1v3eBpLIO5-4) - they match the sketch you did @james-nash.

> We should make it easy for visitors on the Salt website to differentiate between items that have come from the community and our own "core" design system things.
Our content & UI design might use labels & badges to clarify an item's provenance (i.e. "this is a Pepper component" versus "this is a Salt core component")
We might also explore filters on index pages and search, so that visitors can choose to view "all components", "only Salt core component" and so on.

What distinction we make should be between "universal" and "non-universal" use cases. We should avoid a core/not-core hierarchy. Though this will require some cultural change, we want to reach a situation where something can be universally approved and even mandated for use, but not maintained by the core design system team.

Although we're referring to a community index/community catalog, actually our aim should just be to have a single catalog that comprises both Salt team created assets, and community created assets, but with very robust filtering.

A further end goal might be to have user-specific filters. So, e.g., is it possible to identify a logged in user, and show them the curated bundle of components, patterns, etc, that has been defined by the design and dev leaders in their LOB?

**Comment by james-nash** [comment]
> What distinction we make should be between "universal" and "non-universal" use cases. We should avoid a core/not-core hierarchy. Though this will require some cultural change, we want to reach a situation where something can be universally approved and even mandated for use, but not maintained by the core design system team.

Fair enough. We can certainly do that. I suppose that means we'll need some definition of what can be considered "universal" though. Also, is that something the community can decide for themselves (so it might be part of the metadata they push into the main Salt site and we just trust them not to abuse it), or do you envisage the "universal" status to be something the Salt team curates?

I do think also being able to show who maintains a given item is still useful though (and thus, it's also something we might let users search or filter by). So while we may not make it the most prominent piece of information, I still believe it's information we should convey somehow. Certainly, for developer consumers, it will be helpful to know when importing a component might require some additional setup instructions beyond [the ones for our own NPM packages](https://www.saltdesignsystem.com/getting-started/developing). Designers may face a similar scenario too - they'd need to know that component X is in another Figma library than the one they're already using.
