### ISSUE TITLE
Add new icons needed for the FoW experiments and a status icon

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1276]
### Area

UI Components

### The problem

There are several icons we need to add to the library. Some icons are needed to support the current selectables work in progress, others are required to support the 'physical' implementation of the design system as part of the FoW experiments.

### The solution

**Gender**
- Male
- Female
- Gender neutral
- Disabled access / wheelchair user

**Facilities**
- Restaurant/Food
- Snack (e.g. a sweet, a chocolate, or an apple maybe)
- Shop or store front
- Hospital (or more generally medical/medicine)
- First-aid kit

**Status**
- We need a solid variant of the success icon, specifically for use with the checkbox and switch components

### Alternatives and examples
- https://storybook.saltdesignsystem.com/?path=/docs/documentation-icons-icon--page
- https://github.com/jpmorganchase/salt-ds/tree/main/packages/icons/src/SVG

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

----------

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1339
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1347
```

**Comment by ivan-calderon** [comment]
@pseys / @bhoppers2008 sharing the [FoW Exploration icons](https://www.figma.com/file/sixEElEqLWZVOEDvaC0uXb/FoW-experiments-icons?node-id=902%3A193&t=ppGsd0hTl4lSkWkl-1) for review. Please let me know if you have any changes. Thanks.

**Comment by joshwooding** [comment]
Review done, comments are being adressed

**Comment by pseys** [comment]
What's blocking this?

**Comment by pseys** [comment]
@joshwooding would it be possible to get these icons added this week? We've had a request from a dev team who need to use the cart icon and it'd be good to give them an ETA.

**Comment by pseys** [comment]
New icons ready to add (most have default and solid variants):

- Accessible
- Cart
- Hospital
- Medical kit
- Man woman
- Man
- Pot food
- Stethoscope
- Storefront
- Success
- Universal access
- Tote
- Utensils
- Woman
- Woodland
- Crops
- Picnic
- Github
- Signpost
- Marker
- Map

**Comment by origami-z** [comment]
> @origami-z I don't suppose you'd be able to help with this would you?

Yes, i can do this today if no one else has started
