### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1390]
## Description
Support default states and truncation

## Tasks

```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] Fill (Primary, Secondary, Tertiary)
- [x] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [x] Controlled API
- [x] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [x] Supporting site documentation
```

**Comment by origami-z** [comment]
Adjust date to include dev work

**Comment by joshwooding** [comment]
@alycrys assigned

**Comment by origami-z** [comment]
13 Nov - WIP, discussed on page item behaviour, more design discussion. Not much dev changes yet.

**Comment by yunjungyeh** [comment]
✅15 Nov - Catch up with Alina, review/update Accessibility
✅14-15 Nov - Accessibility

✅13 Nov - Component Set Dark
✅13 Nov - Component Set Light

✅13 Nov - Characteristics Dark
✅13 Nov - Characteristics Light
✅13 Nov - Minimum width of Page item
✅13 Nov - Local components Dark
✅13 Nov - Local components Light

✅13 Nov - Review with Ben > update

✅10 Nov - discuss with Ben

✅10 Nov - Catch up with Alina, discussions


✅10 Nov - Update Characteristics
✅9 Nov - Ask Paul questions: regarding compact/truncation icon

✅9 Nov - Update the structure to different component sets

✅8 Nov - reviewed with Ben and discuss questions:

✅8 Nov - Characteristics

✅7-8 Nov - Local components

✅6 Nov - Define Structure and Characteristics

✅6 Nov - Read UITK Pagination page

✅6 Nov - Copy and check UITK Pagination component
✅6 Nov - Create the Component spec file

**Comment by origami-z** [comment]
20 Nov - Discussed characteristics (more waiting input from @bhoppers2008, compact version with/without input). Shouldn't be blocking, can push to lab.

**Comment by origami-z** [comment]
22 Nov - Had a discussion, going ahead with the variant mentioned above. Started designed review, Figma limitation. Dev review (API) started, more docs work

**Comment by yunjungyeh** [comment]
24 Nov - Component Set add to library Dark + QA Playground
24 Nov - Component Set add to library Light

24 Nov - Figma Component Guide: Go to Sticker part! (check form field example) and add change input
24 Nov - Interaction spec Boundary count Alina to review

23 Nov - Interaction spec add Boundary count
23 Nov - Go to sticker Description update

22-23 Nov - Figma Component Guide
23 Nov - Update the Interaction spec about 1-2 digits should be the same

22 Nov - Component Set Dark
22 Nov - Component Set Light

22 Nov - Pagination discussion with Josh/Ben/Alina
22 Nov - After decide if we have compact, add component sets to library LIGHT/DARK
21 Nov - Check with Alina if the Sibling count spec is good

20 Nov - QA Playground Light
20 Nov - Sibling count spec in Interactions Spec
20 Nov - Add component description & links https://www.saltdesignsystem.com/salt/components/index to local components
20 Nov - Update components and characteristics spec
20 Nov - Characteristics update sync with Paul and Alina

**Comment by origami-z** [comment]
6 Dec - pending 2nd round content

**Comment by origami-z** [comment]
11 Dec - Figma library released, PR being reviewed (e.g. question around compact paginator composition).

**Comment by joshwooding** [comment]
18 Dec - Design side done. Need to swam to get it across the line.

**Comment by joshwooding** [comment]
09/01 - Fixing bug, where focus is lost when PageUp/PageDown shortcut is used.

**Comment by alycrys** [comment]
19/01 - Moved to core completed
