### ISSUE TITLE
Foundations - Typography

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1466]
Used well typography helps to enhance readability, establish hierarchy and set a visual tone, resulting in more effective communication.

```[tasklist]
### Tasks
- [x] Create initial draft
- [x] Complete draft
- [x] Request review
- [x] Receive feedback from DS team
- [x] Address internal feedback
- [x] Request review from DXD designers
- [x] Receive feedback from DXD designers
- [x] Address DXD feedback
- [ ] Ready to publish to Salt site
```

**Comment by joshwooding** [comment]
Review tomorrow by design, progress continuing

**Comment by pseys** [comment]
@parsakhan21 i currently have a blocker on this. We need to be able to flag content within the salt site as ‘in progress’ or ‘planned/in backlog’ in order for us to release partially completed content and elicit feedback. The enhancement is currently with James and Joanna

**Comment by shey-v** [comment]
Designs for this are currently in [Figma](https://www.figma.com/file/7Sf9A1yJhlv993ric3NgIO/Site---Birthday-cake%3A-Components-documentation?type=design&node-id=883%3A165585&t=j6OlMOxT2lgLecUW-1).
