### ISSUE TITLE
Foundations - Duration

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1469]
The time between the moment a user performs an action and the moment feedback is given by the system. Consistency in timing provides comfort and can increase trust in a system.

- [x] Create initial draft
- [x] Complete draft
- [x] Request review
- [x] Receive feedback from DS team
- [x] Address feedback
- [ ] Request review from DXD designers
- [ ] Receive feedback from DXD designers
- [ ] Address feedback
- [ ] Publish to Salt site

**Comment by parsakhan21** [comment]
June 23 - Review figma file nav has put together

**Comment by dplsek** [comment]
07/07 - Mike editing content in Figma files for Duration

**Comment by parsakhan21** [comment]
looks like this can be marked as done? @navkaur76 @pseys
