### ISSUE TITLE
Foundations - Density

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1478]
Density relates to the amount of content that can fit on a screen based on the size and spacing of components.

```[tasklist]
### Tasks
- [x] Create initial draft
- [ ] Complete draft
- [ ] Request review
- [ ] Receive feedback from DS team
- [ ] Address feedback
- [ ] Request review from DXD designers
- [ ] Receive feedback from DXD designers
- [ ] Address feedback
- [ ] Publish to Salt site
```
