### ISSUE TITLE
Update site IA (information architecture)

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1483]
We will be publishing new content on the Salt website, so need to revisit our IA and top-level site navigation to ensure we can accommodate that new content.

Obviously, we want our IA to be reasonably stable, but we can't predict the future so the deliverable for this issue is an agreed IA structure we're confident will last at least 6 months. If changes to the IA and nav are needed past that timeframe, that's acceptable.

```[tasklist]
### Tasks
- [x] Agree and document new IA
- [ ] Update site's top-level navigation UI as needed
- [ ] Move/rename existing pages as needed
- [ ] Setup a means to measure how well the new IA is performing (or not)
```

### Known and expected content
Here is a list of pages and sections we already have or expect to publish over the next 6 months or so. The IA we come up with should prioritize accommodating this content in a sensible way. Please add more items if I've missed anything.

* [Homepage](https://www.saltdesignsystem.com/)
* [Component status](https://www.saltdesignsystem.com/salt/components/index)
* Component gallery page (see #1288)
* Per-component docs pages (see epic #562 for more info)
* Per-pattern docs pages (_documentation_ template work for that is being done in #1196, page designs would follow later)
* [Getting started for designers](https://www.saltdesignsystem.com/salt/getting-started/designing)
* [Getting started for developers](https://www.saltdesignsystem.com/salt/getting-started/developing)
* [Roadmap](https://www.saltdesignsystem.com/salt/getting-started/roadmap)
* [Support & contributions](https://www.saltdesignsystem.com/salt/support-and-contributions/index)
* Research approach and methods
* Typography foundations (see #1466)
* States foundations (see #1467)
* Layout foundations (see #1468)
* Duration foundations (see #1469)
* Elevation foundations (see #1470)
* Opacity foundations (see #1471)
* Iconography foundations (see #1472)
* Color foundations (see #1473)
* Division foundations (see #1474)
* Scale foundations (see #1475)
* Modes foundations (see #1476)
* Spacing foundations (see #1477)
* Density foundations (see #1478)
* Data Visualization (see #1388)
* Developer principles (see #1131)
* Content design guidelines (see #1059)
* Characteristics/design tokens
* Salt team page?
* Contribution guidelines
* What is Salt?
* Who is Salt for?
* The ecosystem
* Partners (might eventually overlap with the proposed community showcase - see #1209)
* Case studies
* FAQ

**External links**
* [GitHub](https://github.com/jpmorganchase/salt-ds)
* Blog (on Medium)
* [Figma community page](https://www.figma.com/@jpmorgan_salt)
* [Release notes](https://github.com/jpmorganchase/salt-ds/releases) (on GitHub)

**Comment by james-nash** [comment]
Copying some internal discussions about the new IA below as comments for future reference. Please continue the discussion in this issue via comments.

**Comment by james-nash** [comment]
From @shinytoyrobots on 30. March:

> As @JoanaMMoreira demo’ed yesterday, the Salt site has been rebuilt on Mosaic architecture.
>  
> To follow up on that work, now we can start looking at expanding the scope and scale of our content – both to provide guidance to design system users, and also to influence the ongoing design and development work of the site to be more content-driven.
>  
> I put together a draft sitemap as a potential starting point; keeping in mind that we can iterate quickly and revise based on feedback and analytics, as we create content.
>  
> ### About Salt
> * What is Salt?
> * Who is it for?
> * The ecosystem
> * Our roadmap
> * Releases
> * Partners
> * Case studies
> * Our research approach
>  
> ### Getting started
> * Designers
> * Developers
> * Contributing
> * FAQ
>  
> ### Guidelines
> * Content
> * Architecture
>  
> ### Principles
> * a11y
> * Density
> * Color
> * Typography
> * Etc…
>  
> ### Toolkit
> * Components
> * Patterns
> * Tokens
> * Design kits
> * Community catalog
> * Icons

**Comment by james-nash** [comment]
From @sion-docs on 31. March:

> Looks good.
>  
> In terms of content, with the new Partner initiative I think we need to be engaging users a bit more and even giving them a voice. Case studies moves towards this, but regular blogs and things like interviews would be a really good way to make them feel part of a dialogue rather than them just getting the content we deliver them. Eventually if we could curate things like videos or podcasts where our partners are the ones telling other users how they used Salt that would be great.

**Comment by james-nash** [comment]
From @shinytoyrobots on 3. April:

> The discussion I’ve had with Tanya around the blog, and my general preference, is to use an external blogging platform like Medium or Substack. Several other design system teams do this (Polaris, Carbon, etc).
>  
> It provides greater discoverability, it reduces the need for us to engineer anything in our site (we can, of course, link out). We can connect articles to related topics, but it should be more about thought leadership imo, and certainly less focused on “news of updates/releases”.

**Comment by james-nash** [comment]
From Mitch Rose on 3. April:

> I agree an external platform with a focus on thought leadership and case studies is the best approach for the blog.

**Comment by james-nash** [comment]
From @james-nash on 3. April:

> Thanks @shinytoyrobots  for kicking off this thread and everyone else for chiming in.
>  
> A few thoughts:
>  
> * I agree with @pseys’s suggestion of using “Foundations” over “Priniciples”
>      * With the slight caveat, that if we had a set of overarching principles (akin to SalesForce Lightning’s “Clarity, Efficiency, Consistency & Beauty”), we’d still need a “Principles” page somewhere. But the stuff we have about usage of color, typography, space, etc. feels more at home in a section labelled “Foundations” IMHO.
> * I agree with @bhoppers2008’s suggestions around a11y content (i.e. surface it where relevant – e.g. on component pages or design foundations.
>     * I also second his suggestion of having an a11y page under guidelines that outlines the higher-level approach or motivations
> * On the subject of blogging, I’m certainly keen for us to have one and to use it to publish thought leadership content.
>     * I am a little weary of using a 3rd party platform like Medium to do it though. Yes, they’re convenient and have big audiences. But we’re then also subject to the whims of an external company who wants to monetize our content. It might also make automated integrations of blog posts into other sections of our site harder. For example, let’s say we have a blog post that somehow relates to Data Grid. Wouldn’t it be neat if the Data Grid component page automatically displays a link to that post (and vice versa). It’s probably still doable via APIs, but we’ve then got to align tags (or whatever metadata connects those things) on 2 separate platforms in order for those kinds of integrations to work. Perhaps we can aspire to the [POSSE](https://indieweb.org/POSSE) model (Public (on your) Own Site, Syndicate Elsewhere). We could have our own blog within the site, which has the canonical versions of the posts. But we (perhaps with the help of automation) publish copies in places like Medium to reach a wider audience.
>     * FWIW, I wouldn’t object to starting with only an external blog, but I’d very much like the longer term goal to having our own blog as the official source.
> * While agree with grouping components, patterns, tokens, etc. into one section, I’m not sure about calling it “Toolkit”. I guess it might be familiar to JPM folks who have experience of UITK. But, to me at least, the word “tool” in the context of design systems makes me think of applications that consumers use to get stuff done (e.g. Figma, IDEs, plug-ins, CLI utilities, etc.). I therefore think of components, patterns, tokens, etc. as static things we give to consumers to be used via their tools. Carbon calls the equivalent section on their site “Assets”, which feels like a better fit to me. However, I’m also weary of us already copying lots of ideas from Carbon, so if anyone has a better suggestion I’m all ears!

**Comment by james-nash** [comment]
From @shinytoyrobots on 3. April:

> Just on that final point…
>  
> Using “Toolkit” is definitely used primarily to maintain a thread between UITK and Salt. I think there’s some perception benefits in doing so.
>  
> I agree “Assets” (or similar term) might be more fundamentally accurate term.
>  
> I guess it’s a discussion about both how much importance we want to place on maintaining that UITK -> Salt thread, and how we might go about that.

**Comment by james-nash** [comment]
From Mike Brown on 3. April:

> Thanks for all the feedback around the IA. We’re going to take the suggestions and use it to build out a finalised version, working with the research team to find out what works best as our approach.
> 
> On the blog front, I lean towards Medium but appreciate James’ note that we are at the whims of a third party. My concern is whether we would be able to reach the same size audience without Medium, and publishing in two places could lead to confusion around which link to publicise and share. I like the idea of starting with Medium and moving to an official blog later, especially in the early stages as we’re looking to build excitement externally.
> I plan to build out a content strategy that we can use to make the case for an external blog — would be great to use it to walk readers through unique development challenges, or thought leadership pieces like Robin mentioned.

**Comment by james-nash** [comment]
From @shinytoyrobots on 3. April:

> Yes – move ahead and then refine would be my aim.
>  
> I would like our research to be almost exclusively focused on insights and feedback based on something we’ve built, rather than something we’re thinking of building. 😊 i.e. we have our own hypothesis on why we’re doing something, and the impact it will have, and we should either validate or invalidate that based on feedback on our initial release.
>  
> So, in this case – we internally confirm the top level sitemap IA as a team, build that based, and research the impact on our defined aims and on our OKRs.

**Comment by james-nash** [comment]
From Mike Brown on 4. April:
 

> I have drafted the below IA based on Robin’s draft and some further research:
> * Other design system sites separate out patterns and components to provide fast access to each section
> * Guidelines and foundations merged into one to cover similar types of content that will be accessed less frequently
> * Dynamic content (community catalog, blog) given greater prominence
>   
> ### About Salt
> - What is Salt?
> - Who is it for?
> - The ecosystem
> - Roadmap
> - Releases
> - Partners
> - Case studies
> - Our approach
> 
> ### Getting started
> - Designers
> - Developers
> - Contributing
> - Design kits
> - FAQ
>  
> ### Foundations
> - Content
> - Architecture
> - A11y
> - Density
> - Color
> - Typography
> - Tokens
> 
> ### Components
> 
> ### Icons
>  
> ### Patterns
>  
> ### Community catalog

**Comment by zdxd** [comment]
@mikearildbrown

**Comment by bhoppers2008** [comment]
@mikearildbrown I like it. Couple of thoughts:
- The current Salt site has 'Support' in the navigation. It's very easy to find atm and could be important during the next 2yr migration. Thoughts on keeping that in the nav?
- There are 7 items (potentially 8 with Support)... is that too much for the site nav?
- Bundling everything into Foundations concerns me a little. @pseys's approach to the new foundations pages forms a sort of guide to visual design using the system. Will it be diluted by putting other 'stuff' in there?
- - Random suggestion...Should/could foundations be in Getting started, under 'Design' and 'Dev', depending on what the foundation relates to (design foundation or tech foundation)? How important is it that 'Foundations' is top level?
- - Could A11y be in Getting Started? I'm still not sure what this 'page' would document, but it it's our strategy for accessibility perhaps this might be an appropriate section?
- Whilst it's not high priority, can we pencil in a place for Training content?

**Comment by james-nash** [comment]
We do something similar already:

* Our always-present app header shows only level 1 links
* Pages within "Getting started" add a left-hand vertical nav with level 2 links (and our components section will be doing the same)

What I meant was, perhaps we might consider having an _always-present_ nav that accommodate more links at once. That may or may not be a vertical nav.

**Comment by james-nash** [comment]
FYI: As mentioned in the issue description above, the priority here is to come up with an IA that's good enough to house what we anticipate adding over the next 6 months or so.

If our IA can live longer than that, that's great. But, if we need to significantly rejig it at that point to accommodate new content and/or in response to user feedback, then that's fine too.

To help inform this discussion, I'm therefore gathering a list of existing and expected content we expect to publish on our site over the next couple of quarters. I've added it do the issue description above and will refine/update as I find out more and we begin to prioritise things.

For now, it's a big list of all content-related issues we already have and a few other things that have been talked about here and there.

Feel free to add more items that I've missed.

**Comment by zdxd** [comment]
@shey-v for visibility

**Comment by bhoppers2008** [comment]
@mikearildbrown Looks good.

1. Can we agree what A11y will be. If it's just us clarifying our stance on accessibility at a strategic level should it be in getting started?
2. What's the reason for community catalog as a separate area of the site? Should community catalog just be a view in the component and pattern areas respectively? Seems like extra work for consumers to find 'stuff' if we're separating community components/patterns into a different part of the site from core components/patterns.

**Comment by james-nash** [comment]
@mikearildbrown That structure's looking good. I'm a little confused by what "Branding" and "Content" are doing alongside Salt though. Perhaps that's what you meant by this:

> we have three pillars to the site and Salt is one of three

Can you elaborate? The site is the _Salt_ site. Are you suggesting there may be additional branding and content sites at some point?


@bhoppers2008, yes, I think we need to flesh out what a11y page(s) and content we anticipate having. I would suggest we could look into producing some or all of the following:

* **A11y advice for Salt consumers** (could probably like under "Foundations" in Mike's suggested IA). This page/section could cover stuff like:
    * What a11y concerns Salt does and does _not_ take care of for you? (i.e. make it clear there's still a fair amount of responsibility on consumers to get it right)
    * Suggested approach to incorporating a11y into your overall project (i.e. consider it from the start - don't leave it to the very end)
    * Links to useful resources and further reading (e.g. W3C WAI patterns, Deque university, Microsoft's Inclusive Design site, etc. etc.)
* **Statements about Salt's own a11y conformance & goals** (this probably belongs somewhere under "About Salt" and may not even warrant a whole page, but could be a section somewhere)
     * Something along the lines of: "the Salt components and theme aim to meet or exceed all relevant WCAG 2.1 success criteria. If you find issues, please report them here. etc. etc."
     * Note that this would be about what our DS itself (React components, Figma libs, etc.) supports - not the Salt website itself (which is a thing built with Salt).
* **Per-component a11y info** (we already have a tab for this in our upcoming component page layout, but I think there's more content that could eventually live in there):
    * Best practices: I.e. stuff you need to know when using this specific component (e.g. on buttons we mention about when you do/don't need an accessible label for an icon in the button)
    * Keyboard usage: Document the supported keyboard interactions that the component has
    * Known limitations & deviations: List of a11y limitiations (e.g. due to 3rd party dependencies out of our control) and/or intentional deviations from the standards 
    * Known bugs: List of open a11y bugs on this component (stuff we acknowledge is a bug and we intend to fix)
* **Salt website accessibility statement** (probably a footer link alongside stuff like "Terms of use" and "Privacy policy").
    * This would be outlining the a11y commitments the Salt website makes, known issues, how to report a problem, etc.
    * See https://www.w3.org/WAI/planning/statements/ for more info on a11y statements in general
    
Beyond that, I guess there may be lots of little ad-hoc a11y mentions and tips in relevant sections. For example, our color foundations docs probably should say something about how to use our characteristics to achieve sufficient contrast rations, the typography foundations might say something about minimum text sizes and honoring the user's default text size preferences, etc. etc. But, I'd consider those just part of those other pages' contents and thus not standalone things we need to write and accommodate in our IA / nav.

**Comment by james-nash** [comment]
> What's the reason for community catalog as a separate area of the site? Should community catalog just be a view in the component and pattern areas respectively?

Yes, that's my expectation too. Rather than a single "community catalogue" somewhere on a our site, I want us to expand sections like Components, Patterns, etc. to be able to list satellite DS's components / patterns / etc. alongside our own. I've written up the concept in this epic issue: #1205

**Comment by shinytoyrobots** [comment]
There is some confusion here. Branding and Content may be broader pillars of a design industrialization "umbrella" of sites and services, but that is a separate consideration from how we build out the Salt site.

The community index is, most likely, going to be visible only internally - as I would expect the assets there to be broadly business specific and not open sourced. But we should be moving towards convergence of those indices. And I would argue that actually we want to break down the distinctions between "core" and "community" over time, to continually further democratize the contribution model.

The best analogy I can draw is something like the AWS catalog - where everything exists within the same index, but there are clear markers of that is AWS and what is 3rd party produced/maintained.

**Comment by shinytoyrobots** [comment]
I think it ends up being practically irrelevant to make clear the three pillars until we have at least two pillars. ;) (In the sense that it doesn't have a significant impact on how we present the Salt site itself).

I think the robustness of content and the numerous categorizations implies the need for a vertical left hand navigation rather than a top nav - we'll end up forcing it to be too cluttered.

Refining your previous proposal with most recent thoughts...

**Top navigation**

- Home (logo on far left)
- Search bar
- (future) "site switcher" to move, e.g., between pillars

**Left navigation**

- About Salt
    - What is Salt?
    - Who is it for?
    - The Salt ecosystem
    - Roadmap
    - Releases
    - Partners
    - Case studies
    - Research approach and methods
    - News
    - Blog
    - FAQs

- Designing
    - Get started
    - Design kits
    - Tutorials
    - Other resources

- Developing
    - Get started
    - Tutorials
    - Other resources

- Contributing
    - Introduction / overview
        - must include Contributor licensing
    - Bug fixes
    - Feature requests
    - Documentation
    - Components
    - Patterns
    - Icons
    - Tools and add-ons

- Guidelines
    - a11y
    - Architecture (high level developer / code architectural considerations - this could also go in the "Developer" section)
    - Content

- Foundations
    - Density
    - Color
    - Typography
    - Tokens
    - etc

__Assets__ (nav section title, but not a link)
- Components
    - Index
    - Accordion
    - Button
    - etc...
- Patterns
    - Index
    - Login flow
    - Dashboard
    - etc...
- Icons
- Community catalog

*Footer*

- Terms of use
- Privacy policy
- Feedback
- Bug report
- Feature request
- Contact us

**Comment by shinytoyrobots** [comment]
We need to start populating some of this content - especially getting our roadmap updated and published.

@shey-v @JoanaMMoreira - it feels like this requires at least an initial implementation of https://github.com/jpmorganchase/salt-ds/issues/1054 (Vertical Nav) to cater for the expanded content. What do you think?

**Comment by bhoppers2008** [comment]
Now that we've added Nav Item to the backlog perhaps we can get together @shey-v @JoanaMMoreira to discuss feature requirements to support Vertical and Horizontal Navigation patterns. @joshwooding and I have already started knocking a few requirements together, including:
- Orientation support (vertical, horizontal)
- Activation bar at top–rather than bottom–aligned to navigable characteristic.
- Activation bar custom colour support.
- 'Always on' as optional (ie., Bar doesn't have to stay visible/no toggle state).
- # 'Level' to drive label inset amount.
- 'Parent item' as bool to determine presence of arrow (to right in vertical nav, at bottom in horizontal nav).
- Pattern examples of stacked nav items, horizontal and vertical.
- Pattern example of nav item 'nesting'.
- Pattern example of nav item with nested cards (MCP).
- Pattern example of nav item with nested mega menu (MCP).

**Comment by JoanaMMoreira** [comment]
Sounds good! It would also be good to loop in the Mosaic team so they can add our component into Mosaic

**Comment by mark-tate** [comment]
re: FAQs

In a discussion with a potential stakeholder they asked the following questions
By no means a full set but a good sample created by a real user.

1. what browsers do you support?
2. what framework dependencies do you have?
3. how often do you release breaking changes?
4. what accessibility standard do you support?
5. how big is the core development team?
6. how do we add components to our own product which might not exist in Salt Design system?

**Comment by shinytoyrobots** [comment]
I agree that we can't contain more content than that in a horizontal navigation. Though I think we capture a lot of extra richness here.

I'd re-order `Home | **About** | Getting started | Foundations | Components | Support and contributions`

(We could probably also give ourselves a little more flexibility if we dropped `Home` as an actual nav option and just used the top left logo as that fairly standard pattern)

**Comment by delmej** [comment]
Yes, we're planning to do some updates and a release for the guide - it makes sense to do this as part of a migration to Salt (I've been chatting to James about this). The amount of content in the guide is significant, meaning that although we plan to build it out, it already feels like it qualifies as a pillar. One other thing is that we've just been promoting the fact that we've moved Content to a global nav item on UITK, so if we're now going to be redirecting users to Salt, it will seem odd UX for them to find Content a bit hidden under Foundations when they get there.

**Comment by delmej** [comment]
Ha - sorry - I meant Guidelines, not Foundations!

**Comment by joshwooding** [comment]
@mikearildbrown everything should be possible. Did you have any concerns?
