### ISSUE TITLE
Migration & Community: Research Sponsor User Programme

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1526]
Program Q2-4

```[tasklist]
### Tasks
- [x] Create research approach/indicative requirements on participants to be signed-off by @shinytoyrobots  and shared with sponsor user tems [in progress, see comment 17/04]
- [x] Draft research brief & upload for research PMs tracking
- [x] Author repeating "experience of adoption" interview questions
- [x] Gather team feedback (devs for devs ect)
- [x] Create and share engagement memo and location for data storage for the sponsor user program
- [ ] Decide whether early May interviews used for pattern docs or community index
- [ ] Schedule early May interviews with Salt-assigned team member and interviewee
- [ ] Early May interviews and analysis (part 2 likley tracked by another ticket)
```

**Comment by zdxd** [comment]
Inital ask to team leads to provide indication of who is in the team and how they contribute to the delivery of the product (at role or discipline level). 

Propose 45 min interview with representative sample of team in early May. 
- Part 1: first 15 min of interviews will set a baseline for longitudinal data collection on the team's experience of adopting and using the design system. 
- Part 2: 

Propose that Salt dev or developer assigned to sponsor team attend inital interview. 

Additionally, propose that when our team engages with a sponsor user team they add a memo to file so we can collect this as "naturally occurring" data and draw on as a team. 

Use of sponsor user teams in next two months will be

**Comment by zdxd** [comment]
**Team Call Updates**
Parsa - April 17 - robin is scheduling calls with teams. Aim - consistent data collection

**Comment by zdxd** [comment]
To what extent is the design system supporting their business deliverables, how closely aligned is SALTs delivery of components and patterns with their requirements

**Comment by joshwooding** [comment]
In Progress, Annia picking up. Robin to cover during time off

**Comment by zdxd** [comment]
@parsakhan21 research work in progress - & catching up with Robin this afternoon on meetings w/ teams

**Comment by zdxd** [comment]
created interview memo / template which is with Robin for review alongside brief

**Comment by parsakhan21** [comment]
@zdxd hi zoe, did you ever receive feedback on this from Robin? 

FYI @shinytoyrobots

**Comment by zdxd** [comment]
yep Robin reviewed, protocols done, awaiting the org / kick of of meetings with sponsor users to start data collection

**Comment by zdxd** [comment]
Hi @parsakhan21 what's the update on sponsor users?

**Comment by tadxd** [comment]
Combining workstream with Designer-Developer workflows

**Comment by tadxd** [comment]
Oct-2: Backlogged / sunset workstream in beginning Q3
