### ISSUE TITLE
Evaluation, OKRs, and Tracking | Post-Training / Knowledge Share Surveys

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1527]
Evaluate the satisfaction and value of product and learning initiatives for evaluation and OKR reporting 

```[tasklist]
### Tasks
- [x] 	Design regular user satisfaction survey
- [x] 	Design set of reusable surveys for product initiatives e.g., feedback on the DS curriculum, sentiment, and applicability (does it overcome the right kinds of skills gap, baseline pre-training and post)
- [x] Gather approval for designed surveys.
- [x] Field surveys
- [x] 	[Q3] Set up dashboards and processes to review initiative data in one place
```

```[tasklist]
### Deliverables
- [x] Qualtrics survey instrument
- [x] Qualtrics dashboard
```

**Comment by zdxd** [comment]
@bhoppers2008 could you update on need from training perspective - thanks!

**Comment by zdxd** [comment]
April 24 in progress - aiming for task 1 (overall sat) submitted for approval prior to ooo on 27th of April

**Comment by zdxd** [comment]
@parsakhan21 surveys designed & starting approval process

**Comment by parsakhan21** [comment]
June 2 - in progress

**Comment by bhoppers2008** [comment]
> @bhoppers2008 could you update on need from training perspective - thanks!

@zdxd assume this is the survey you asked me about in Teams?

**Comment by zdxd** [comment]
@bhoppers2008 yep! Thanks for the feedback

**Comment by zdxd** [comment]
minor update here - surveys have been created and research ops are reviewing prior to submission for approval

**Comment by zdxd** [comment]
followed up with Alexandra - no updates

**Comment by parsakhan21** [comment]
July 14 - list of attendees form iems - july 18 (first survey - typography)

**Comment by tadxd** [comment]
Jul 24 - survey is live for Typography; reminder goes out tomorrow. encouragement from team to complete requested. closes out on friday.

**Comment by tadxd** [comment]
Jul-28: survey closing today. low response rate; coordinating with CLG team to see if there's another survey route we can take.

**Comment by tadxd** [comment]
Aug 2: Low response rate; reporting threshold not met and so will wait to share dashboard until next session. Meeting with CLG team to review best practices/automation moving forward.

**Comment by tadxd** [comment]
Sep 8 - survey launched for Forms. Currently live
