### ISSUE TITLE
Usability: Reporting on Research

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1529]
```[tasklist]
### Tasks
- [x] Define how results for component and pattern tests are summarized for SALT website guidance
- [x] Document process (e.g., peer review before publication) for reported results
- [ ] Add page to website
```

**Comment by zdxd** [comment]
@mikearildbrown Svetlana and Rufaro did work on this last year - maybe we can find it to get started?

**Comment by zdxd** [comment]
okay @mikearildbrown let's catch up and sketch out the structure for "research approach and methods", general template for "methods" and start to think about how results might be reported on within technical docs (I have found some good examples from Goldman and MUI)

**Comment by zdxd** [comment]
@mikearildbrown & I are working on

"Our approach to research" page to live within "about us" section of site. This will outline the usability program and any pillars of research/guiding principles we want to mention. I have shared draft with Mike who will edit prior to creating MDX for site. 

Linking research into component docs @sion-docs has recent research results for button & status indicator which he will review for relevance to docs. Expect that some info from results will be inc in first set of component docs & that we will make some edits to research approach to further address/drive guidance

**Comment by parsakhan21** [comment]
June 9 - edited the post that will be released to site; waiting to deploy

**Comment by james-nash** [comment]
Great!

Am I right in thinking this will be the "About Salt" > "Research approach & methods" page we identified in the [IA discussions](https://github.com/jpmorganchase/salt-ds/issues/1483#issuecomment-1544043626)?

If so, I'll open a PR to add an MDX-ified version of it. I may as well move the roadmap page while I'm at it, as that's intended to live within the About section too.

**Comment by zdxd** [comment]
Yep that's it!

**Comment by parsakhan21** [comment]
June 30 - add page to website ; dependencies need to be addressed

**Comment by james-nash** [comment]
Moving this to blocked as it depends on: https://github.com/jpmorganchase/salt-ds/issues/1923
