### ISSUE TITLE
pattern usage doc template

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1532]
```[tasklist]
### Tasks
- [x] Shey / Zoe Independently review MTK research and pull out key themes/ideas
- [x] Shey to do additional desk research on what competitors are doing
- [x] Meet Zoe / Shey
- [ ] Peer review the content block approach for pattern template
- [ ] Test template with Navigation pattern
- [ ] Collate & bring together to draft MDX template
```

**Comment by zdxd** [comment]
@shey-v & I catching up tomorrow

**Comment by zdxd** [comment]
Docs to review and draw themes/ideas out of 

Pattern Lib Workshop: 
https://www.figma.com/file/YPpNOKLf4WQDbOifDafoL5/Pattern-Library-Workshop?node-id=0-1&t=wlASsaqdSxJpg6FY-0

MTK Pattern Lib: 
https://www.figma.com/file/53Sf8iOEq22zimhg1iKjdK/MTK-pattern-library?node-id=93-104559&t=f1aRNryanJO8vKky-0

**Comment by joshwooding** [comment]
Progress continuing, (see tasks above)

**Comment by zdxd** [comment]
Discovery should cover exploration of and refining of definition of pattern

**Comment by shey-v** [comment]
Discovery and research ongoing - meeting scheduled to catch up with Zoe this Weds to discuss findings

**Comment by shey-v** [comment]
Zoe & Shey met to discuss independent desk research, found similar themes and now working on outlining a draft structure for the patterns page.

**Comment by shey-v** [comment]
Research consolidated and shared with Robin. Shey working on competitor analysis.

**Comment by shey-v** [comment]
Work in progress - drafting out a proposal for the general structure of patterns docs based off of research done.

**Comment by shey-v** [comment]
Reached out to Oren Dayan and Julie East (Risk & Payments) to gather further insights on what is required from our consumers for pattern docs. In meantime, I'm putting together a draft template for various content blocks or 'sections' for the template in Figma.

**Comment by zdxd** [comment]
@shey-v  i'm going to split this out since the usability aspect is on hold / no longer planned for this Q

**Comment by parsakhan21** [comment]
May 12 - work in progess

**Comment by shey-v** [comment]
May 17 - have socialised with Ben, Robin, James and Jo for feedback. Will be pausing this piece of work until the Nav item component is ready, which will be my main focus.
