### ISSUE TITLE
Refine contact & support channels for UITK

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1557]
There are a number of ways UITK consumers can reach out to the team: various email distribution lists, internal chat rooms, internal forums and/or directly raising tickets on our backlog. Historically, we've not specified which channels to use for which purposes. Consequently, our consumers tend to use all of them interchangeably for getting help, making product inquiries, reporting bugs and requesting new features.

This causes the following problems:

* Confusing to consumers
* Monitoring all the channels is time consuming because it's largely manual
* Tracking stats (e.g. bug fix turnaround times, response times to queries) is difficult, because not all channels are geared up to track such things
* There is a maintenance overhead to keeping all our email distributions lists up to date as people join or leave the design system team

We therefore need to review and refine how our consumers can get in touch with us. Most likely, we can do something along the lines of what we have with Salt, where our [support & contributions page](https://www.saltdesignsystem.com/salt/support-and-contributions/index) clearly directs people to specific places for different kinds of requests.

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1591
- [x] Setup or reconfigure channels as needed by the new strategy
- [ ] Reduce the number of email distribution lists (and ensure we update mentions or links to them as needed)
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1616
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1640
- [ ] Update design system team processes & documentation as needed
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1641
```

**Comment by parsakhan21** [comment]
April 20 - in progress; draft strategy for how teams get in touch and how we support

**Comment by james-nash** [comment]
@parsakhan21 FYI, I've converted this to an epic and made the first task (#1591) into an issue.

Once that one's done, we can convert the remaining tasks into issues as needed.
