### ISSUE TITLE
UITK to Salt high-level migration guide

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1584]
Produce a UITK to Salt migration guide and publish it on the internal UITK website.

The target audience is managers (PMs & POs) and practitioners (designers & devs) who have existing UITK applications and want to migrate them to Salt.

Things to cover could include:

* _Very briefly_ Why should you invest time to migrate your UITK app to Salt? (and what are the risks if you don’t migrate)
    * A separate article will cover this in more detail, so this could just mention and link to that
* How much effort will it take?
    * Tips for assessing how complex your migration will be (which could link to more detailed guides/examples as appropriate)
    * E.g. Do you override UITK styles a lot? Do you use DataGrid? Do you use a micro front-end architecture? Etc.
* UX considerations and their implications
    * Is it a purely tech-driven migration where you want to keep the Salt UI identical to the UITK one, so your users don’t notice?
    * Do you want to use the migration as an opportunity to revamp or tidy up your UI?
    * If you have UITK-based Figma designs, do they need to be migrated or not?
* Does it matter what version of UITK you are on? Do we want consumers to upgrade to latest UITK first and then migrate to Salt, or can they always go direct to Salt?
* Outline and compare possible approaches. E.g.:
    * All at once
    * Piece-by-piece “[Ship of Theseus](https://en.wikipedia.org/wiki/Ship_of_Theseus)”-style

```[tasklist]
### Tasks
- [ ] Produce first draft in Word (@james-nash to do this)
- [ ] Review & refinement by content team
- [ ] Publish on UITK site (may depend on #1574)
```

**Comment by mark-tate** [comment]
I have an internal doc for this, please reach out.
We could close this ticket and iterate on improving the existing doc, which is a living doc and so not worth tracking.

**Comment by james-nash** [comment]
Fine by me. Though I do think we should ensure we link to that doc from the UITK site (I know there's already work underway to add a Salt page/section there anyway, so we just need to ensure it's included there).

**Comment by origami-z** [comment]
Salt page added on UITK site, closing
