### ISSUE TITLE
Usability Testing | Patterns Documentation

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1649]
Provide an evidence-based set of recommendations re: understanding of the users and the documentation design forward. 
Identify elements of documentation design needed to facilitate efficient and error free work for design system users. 

```[tasklist]
### Tasks
- [ ] Develop research brief
- [ ] Coordinate with Design re: prototypes to use in testing
```

```[tasklist]
### Deliverables
- [ ] Research brief
- [ ] User interviews protocol
- [ ] Recommendation report
```

**Comment by zdxd** [comment]
pattern docs on hold

**Comment by tadxd** [comment]
Oct-6 - picking workstream up; planning session today

**Comment by tadxd** [comment]
Oct-11: Held planning session with @mikearildbrown @shey-v; working session next week to confirm consistencies/inconsistencies with current docs + identify design attributes to test

**Comment by tadxd** [comment]
Oct-30: awaiting wireframe from design for testing.

**Comment by origami-z** [comment]
3 Nov - Meeting next Monday, test with MDX instead of Figma

**Comment by joshwooding** [comment]
Meeting had earlier this week. Button Bar pattern to be used an an example.

**Comment by joshwooding** [comment]
Round of edits done on Button Bar pattern page. Usability testing date to be arranged soon.

**Comment by origami-z** [comment]
20 Nov - working on test script

**Comment by origami-z** [comment]
22 Nov - discussed with Renae, testing script

**Comment by origami-z** [comment]
24 Nov - testing scripts, same above

**Comment by origami-z** [comment]
27 Nov - waiting for feedback from Renae

**Comment by origami-z** [comment]
8 Dec - Links being review, to be launched on next week

**Comment by joshwooding** [comment]
18 Dec - Meeting tomorrow.
