### ISSUE TITLE
Stepped Tracker v1

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1664]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [x] Horizontal oreintation
- [x] Basic stepped tracker (Default, In progress, Complete)
- [x] Label truncation + tooltip support
```
*Dependency*:
- Color update requires basic validation
- Progress Indicators

**Comment by parsakhan21** [comment]
June 30 - kick off 6/30

**Comment by el-dav** [comment]
@joshwooding @bhoppers2008 @ivan-calderon 

Could I get clarification on something. Is it possible to move onto a step without the previous one being completed. E.g. something like: (complete, incomplete, active, incomplete)?

✓-----ο-----●-----ο

I could see this being useful if some steps are skippable, or if you're able to fill out the steps out of order, but I couldn't see this behaviour in the UITK examples

**Comment by bhoppers2008** [comment]
> @joshwooding @bhoppers2008 @ivan-calderon
> 
> Could I get clarification on something. Is it possible to move onto a step without the previous one being completed. E.g. something like: (complete, incomplete, active, incomplete)?
> 
> ✓-----ο-----●-----ο
> 
> I could see this being useful if some steps are skippable, or if you're able to fill out the steps out of order, but I couldn't see this behaviour in the UITK examples

@el-dav would suggest pushing to a later version... my rationale is that navigating forward and backward through non-consecutive steps is probably something worth supporting but will require extra work (both dev and design). I'd opt to keep as a strict linear flow for the time being and enhance it with non-consecutive navigation at a later date.

**Comment by el-dav** [comment]
For me I'd ideally want it to be considered earlier as currently the UITK implementation can be a bit confusing.

For example:

```jsx
<SteppedTracker activeStep={2}>
  <TrackerStep completed={false} />
  <TrackerStep  />
  <TrackerStep  />
</SteppedTracker
```

Shows: ✓-----✓-----●

Also...

```jsx
<SteppedTracker activeStep={0}>
  <TrackerStep />
  <TrackerStep />
  <TrackerStep  completed={true} />
</SteppedTracker
```

does show: ●-----ο-----✓ but the lines are dotted rather than bold

**Comment by ivan-calderon** [comment]
> @joshwooding @bhoppers2008 @ivan-calderon
> 
> Could I get clarification on something. Is it possible to move onto a step without the previous one being completed. E.g. something like: (complete, incomplete, active, incomplete)?
> 
> ✓-----ο-----●-----ο
> 
> I could see this being useful if some steps are skippable, or if you're able to fill out the steps out of order, but I couldn't see this behaviour in the UITK examples

NP, I can take that into consideration and explore this further. Paul and Nav did a great job creating [indication pattern icons](https://www.figma.com/file/CsYtMagw9kYUv1lspVx72s/Indication-pattern?type=design&node-id=1843%3A127961&mode=design&t=AWn7qgefPuXOYq93-1); and that can be useful in this case. However, I don't see that implemented on V1 because that will require a deeper analysis on: the characteristics, what tokens to apply, what tokens are missing, if current indication icons fulfill this component's needs, potential effects on behavior and interactions (clickable elements, keyboard navigation, accessibility consideration for inactive steps), and few other things. So the initial construction will be linear I guess.

**Comment by bhoppers2008** [comment]
@el-dav is it likely to affect the api now? In that case, it would be worth agreeing the user stories (ie., what would the interaction requirement be) to limit breaking changes in the future. But otherwise I agree with Ivan. v1 should be the most basic reasonable implementation that we can release and get feedback on.

**Comment by el-dav** [comment]
@bhoppers2008 It could affect the API. 

For example:
- If a step is only complete or not we might have a prop called `completed` which could be `true` or `false`
- If however we might have more states e.g. `default`, `started`, `completed` then we'd probably instead have a prop called `state` which could take three values of `default`, `started` or `completed`.

It's also possible that even if we don't need to update the API, the behaviour of the component could change which i would regard as a breaking change. E.g. if:

```jsx
<SteppedTracker activeStep={2}>
  <TrackerStep completed={false} />
  <TrackerStep  />
  <TrackerStep  />
</SteppedTracker>
```

went from `✓-----✓-----●` to  `◐-----✓-----●`

**Comment by bhoppers2008** [comment]
> @bhoppers2008 It could affect the API.
> 
> For example:
> 
> * If a step is only complete or not we might have a prop called `completed` which could be `true` or `false`
> * If however we might have more states e.g. `default`, `started`, `completed` then we'd probably instead have a prop called `state` which could take three values of `default`, `started` or `completed`.
> 
> It's also possible that even if we don't need to update the API, the behaviour of the component could change which i would regard as a breaking change. E.g. if:
> 
> ```js
> <SteppedTracker activeStep={2}>
>   <TrackerStep completed={false} />
>   <TrackerStep  />
>   <TrackerStep  />
> </SteppedTracker>
> ```
> 
> went from `✓-----✓-----●` to `◐-----✓-----●`

If it's going to impact the build now, then write out the stories with @ivan-calderon to future proof for coming versions. Those stories can then be the requirements to spec out when we get to that version. It's not a feature we need to build out now though. 

+ @joshwooding

**Comment by parsakhan21** [comment]
July 14 - review PR comments and address accordingly

**Comment by joshwooding** [comment]
21/07 - review comments addressed, ready for re-review. design to review changes to spacing. Ivan to create Figma guidance. will send to content to review

**Comment by el-dav** [comment]
12/07 - PR has been approved by dev and design and merged

**Comment by parsakhan21** [comment]
July 24 

- Characteristics for V1 are complete (I'll be cleaning up the file)
- Component's Figma branches (Light and Dark) are WIP 
- Component Figma guide is WIP
- The goal is to have all the above completed today and ready for a final review. 
- Dev complete - in labs
- Component doc with content for review 

Note: Potential changes in the component design (alignment) shouldn't impact V1. For now, research scoping doesn't include those proposed changes. So, that won't affect the current design

**Comment by ivan-calderon** [comment]
Stepped tracker design files for reference: 

- [Stepped tracker specs](https://www.figma.com/file/r5jCbd7iFfiSGc9wvSfRWM/Stepped-Tracker?type=design&node-id=41%3A1588&mode=design&t=Qwc88Sl6RYXqo3Kf-1) (I've cleaned the file) 
- [LIGHT stepped tracker](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/Ii4UvDwimpnWLpG90aUbw8/Salt-Light-Components?type=design&node-id=9089%3A84780&mode=design&t=pqpifHQ0Go1iGMLn-1) 
- [DARK stepped tracker](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/OJpHsUOyWu4mJ7eyQiyVy9/Salt-Dark-Components?type=design&node-id=6183%3A1616&mode=design&t=tQCQ28h3baKKz5ZU-1) libraries
- [Stepped tracker Figma guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/nixnHByFNyiCUy1Y6Ymtr3/Salt-Figma-Component-Guides?type=design&node-id=2293%3A579&mode=design&t=Qx1u9kBxnkYYp6yI-1)

**Comment by parsakhan21** [comment]
July 25 - Dev: PR has been approved so should be merged imminently (re:remove some functionality from UITK); designs awaiting final review/approval from Ben today

**Comment by bhoppers2008** [comment]
Design review complete... component and guide looks good but we should hide the features that aren't v1 for the time being as MCP at interested in the component and it should reflect what's in prod. Other than that, the component and guide are good to merge.

A couple of questions raised for a new issue/ subsequent release:

- Is step-active ok rather than in-progress for current step ( @ivan-calderon to check with Tara).
- Should we use 'to-do' icon for steps that aren't started?
- Should 'draft' icon be reserved for steps that aren't complete but have been passed and should it be --status-info-foreground (as the pattern)?

**Comment by AnniaT** [comment]
Released to labs. 

Several queries around behaviour currently being looked at.

**Comment by AnniaT** [comment]
to catch up on docs e/ @james-nash @ivan-calderon @el-dav re template.

**Comment by parsakhan21** [comment]
August 2 - released in labs; storybook docs complete; mdx to be filed with relevant examples during component docs sprint week

**Comment by bhoppers2008** [comment]
Figma component and guide published internally and externally.
