### ISSUE TITLE
Tooltip Desktop Support

### ISSUE THREAD

**Issue by ImmanuelBaskaran** [jpmorganchase/salt-ds#1711]
The Tooltip currently cannot be currently used as a pop-out component in a desktop environment

```[tasklist]
### Tasks
- [x] Exploration of solutions
- [x] Evaluation of solutions
- [x] Implementation
- [ ] Story to show Consumer Implementation
- [ ] Tests
- [ ] Documentation
```

Having discussed with consumers we are going down a Provider route to enable this where consumers can pass a floating ui Platform via Context to components such as Tooltip

**Comment by parsakhan21** [comment]
May 26 - documenting exploration results  - aim to finish soon; David - writing code from consumer perspective - how to make it work with what we have now

**Comment by el-dav** [comment]
Work is complete/paused while consumers test out the desktop implementation via a snapshot release. Potential for more work in the future based on feedback

**Comment by el-dav** [comment]
We've had some consumer feedback. Overall the solution and API works for them and they are happy that the same solution can be used for various floating components. There are some additional changes that are required:

Tooltip Feedback
- Tooltip is Flipped (due to modifiers used)
- Tooltip Slightly too high (due to modifiers used)
- Frequency of updates get stale, causing Tooltip to be positioned incorrectly after a window move
- x and y has to be accessed through the style prop, which doesn’t really make sense on desktop
- Don’t have access to width and height in the tooltip

Actions required
- Give consumers a way to update the floating-ui modifiers used
- Give consumers a way to adjust the auto-update behaviour of the tooltip
- Pass x and y as independent properties rather than as part of the style prop
- Pass width and height from floating ui to the tooltip component via getTooltipProps

**Comment by mark-tate** [comment]
Can we break these into Desktop specific features and generic web/desktop component issues? We can then groom/prioritize. For Desktop specific issues, we will need to partner up with our Desktop team but that should not block any features we can deliver through web.
