### ISSUE TITLE
Evaluation, OKRs, and Tracking | Annual UITK & SALT Survey

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1758]
Repeat (modified) version of UITK 2022 survey + short question set around adoption and experience w/ SALT 
```[tasklist]
### Tasks
- [x] Survey Design and Program in Qualtrics
- [x] Survey Approvals
- [x] Collect DL and Draft Email Invite / Reminders
- [x] Final Review with PO
- [x] Field Survey - Launch early Sept and keep open for 2 weeks
- [x] Analyze and Present Results
```

```[tasklist]
### Deliverables
- [x] Qualtrics survey instrument
- [x] Qualtrics dashboard
```

**Comment by zdxd** [comment]
Booked in meeting for peer review w/ survey expert (Fiyin Adesina) on team & working toward approval w/ research ops (Alexandra Ayoob)

**Comment by zdxd** [comment]
same as above

**Comment by zdxd** [comment]
Approved by Alexandra, Morgan Tierney pulling updated distribution list

**Comment by parsakhan21** [comment]
July 14 - in progrses; one final review with robin (july 25 launch )

**Comment by tadxd** [comment]
Jul-28: Still awaiting Jean review/approval. Worried that he is OOO for next few weeks (unless calendar just blocked?) @parsakhan21

**Comment by tadxd** [comment]
21-Aug: teaser incl. in newsletter. cross-referenced DL with newsletter DL. Added those who were on newsletter but not orig DL.

**Comment by tadxd** [comment]
Sep 1 - Launching next week. Prepped and ready to go

**Comment by tadxd** [comment]
Sep-15: Survey live; analysis ongoing

**Comment by tadxd** [comment]
Sep-29: analysis complete; results presentation next week.
