### ISSUE TITLE
Port UITK's content guide to Salt website

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1802]
We want to port the content guide on UITK's internal site to our public Salt site.

### Notes
* The UITK version has a few special features and components that go beyond plain Markdown/HTML and therefore need to replicated on the Salt site (or omitted if they no longer make sense in the context of the UITK site).
* There are some edits and additions to the existing content that need to be applied as part of this work
* There are some new "specialised content" pages to add too.

```[tasklist]
### Tasks
- [ ] **Copy across existing main content** (substituting UITK components for Salt equivalents as needed). Excludes right-hand column content and A-Z filtering functionality
- [ ] **Port right-hand column functionality and content** (adapt/change it as needed to be consistent with how other sections on the Salt site behave)
- [ ] **Apply content edits and add new pages**
- [ ] **Create new overview page card images** (The style of the existing ones would look out of place on the Salt site. Also, we'll need some additional ones for the new pages anyway)
- [ ] **Make list of terms searchable & filterable** (build components to replicate functionality of the "A - Z of approved terms" page.)
```

Note that the UITK content guide displays links to in-page sections within the left-hand vertical nav (if you expand the current page). However, the patterns we've been using for in-page navigation for the Salt site (in Getting started, Foundations and - soon - Components) is to have that at the top of the right-hand column. To keep things consistent, I suggest we use the same approach for the content guide when it's migrated to the Salt site.

Also, the UITK content guide pages feature a link to JPM's internal StackOverflow at the bottom of the right-hand column. We can't link to internal things from the Salt site and I'm not sure there's a relevant public alternative, so I've omitted this from the list of requirements above.

**Comment by origami-z** [comment]
What's the alternative placement for existing "right-hand column" items? Need design input?
