### ISSUE TITLE
Combo Box v3 (multi-select + pills)

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#1858]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
```[tasklist]
### Features
- [ ] Create dependency: Tokenized Input replaced by #2541
- [ ] Multiple selection as pills replaced by #2413
- [ ] Pill group expand and collapse, with truncation replaced by #2414
- [ ] Preselected values, with option to make non-removable
```

**Comment by origami-z** [comment]
Close, replace with per feature issues
