### ISSUE TITLE
Dropdown v2

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#1861]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
```[tasklist]
### Features
- [ ] Validation states replaced by #2357
- [ ] Custom Button Support (partnership feature requirement) replaced by #2358
- [ ] Form Field support replaced by #2359
- [ ] truncation support in List (v3) and Dropdown replaced by #2360
- [ ] add placeholder for Dropdown replaced by #2361
- [ ] customisable list height replaced by #2362
```

**Comment by origami-z** [comment]
Replaced with per feature issues
