### ISSUE TITLE
Stepped Tracker validation states

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1866]
```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] Fill (Primary, Secondary, Tertiary)
- [x] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [x] Controlled API
- [x] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [x] Validation states (Error warning)
- [ ] Modify step
```

**Comment by origami-z** [comment]
Should be covered in #2886

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- changing prop names, deprecate old prop, add new
- docs updated on site

**Comment by tomhazledine** [comment]
* _2024-06-27_ Discussed naming in FED meetup - unresolved
* _2024-06-28_ Discussion in Teams (_"let's name a prop"_): consensus on adding `stage` and `status` props and merging state in-component.
* _2024-07-01_ Waiting on @joshwooding for final sign-off on interaction of `activeStep` with state (see Teams thread)

**Comment by tomhazledine** [comment]
#3584 ready for dev review

**Comment by tomhazledine** [comment]
Addressing review comments re: stories and examples.

**Comment by mark-tate** [comment]
Can we close out by 23/07/24 @joshwooding

**Comment by tomhazledine** [comment]
Approved and merged
