### ISSUE TITLE
Stepped Tracker vertical orientation

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1867]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [ ] Vertical orientation
```
