### ISSUE TITLE
Stepped Tracker previous steps as links

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1868]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [ ] Previous step navigation (New, optional, completed steps as links)
```

**Comment by mark-tate** [comment]
Latte Goal: @jake-costa review any accessibility concerns, docs review by @ivan-calderon

**Comment by jake-costa** [comment]
A11y comments added to Stepped Tracker Figma Specs. @ivan-calderon Ready for review

**Comment by mark-tate** [comment]
Lungo Goal: No dev capacity

**Comment by mark-tate** [comment]
Macc Goal:
QA Kris updates, push a copy to James for approval
Decision on Core sprint/date by EOS

**Comment by bhoppers2008** [comment]
To be scheduled after feedback on Stepped Tracker labs release. Pushing back to backlog.

**Comment by mike-gray-pxd** [comment]
The Stepped Tracker is being used in the Salt Migration pf Trade Processing Systems - image exported from Figma is included - also included is the an exported image of the existing TPS system that is built in Google Web Toolkit and has all the characteristics of an old Windows Application.

**Comment by mike-gray-pxd** [comment]
(Couldn't upload images so linking to Confluence page with them on)

[Images here](https://confluence.prod.aws.jpmchase.net/confluence/x/OMmNDwE)

**Comment by bhoppers2008** [comment]
Spoke with @mike-gray-pxd who will provide some more detailed requirements and edge cases for forward/back navigation within the stepper.

**Comment by mike-gray-pxd** [comment]
Hi @bhoppers2008 - I added some notes to the images in the Confluence page above.

"Transaction processing is a '4 eyes' process where a maker's work is checked by a 'checker'.
The transactions have between 15-20 steps.
In the current windows based UI (above right) they're horizontal tabs.
In the proposed Salt update (above left) it's the stepped tracker.

For both roles - but particularly the checker role - there is an operational need to navigate the steps non-linearly.
Clicking 'next' 15 times to get from 1 to 15 isn't desirable or operationally efficient."

([link to comment and images](https://confluence.prod.aws.jpmchase.net/confluence/spaces/CIBPXD/pages/4555917624/Stepped+Tracker+vs+Google+Web+Toolkit+Windows?focusedCommentId=4863270157#comment-4863270157))

**Comment by mark-tate** [comment]
Technically feasible but requires a11y implementation.

To be made an example in Stepper docs.

**Comment by jake-costa** [comment]
A11y feedback was provided in Figma. Will check with @ivan-calderon to see if anything else is needed.

@mark-tate Do we already have feedback on Stepped Tracker labs release?

**Comment by bhoppers2008** [comment]
Low priority until UITK Parity is complete. Moving back to backlog.

**Comment by bhoppers2008** [comment]
Migrated to Jira.
