### ISSUE TITLE
Stepped Tracker sub-step support

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1869]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [ ] Sub-step support
```

**Dependency**: New; requires design

**Comment by tomhazledine** [comment]
See #2886 for update details.

**Comment by mark-tate** [comment]
Currently in PR, please provide feedback
https://github.com/jpmorganchase/salt-ds/pull/3803

**Comment by mark-tate** [comment]
Latte Goal: PR review done if capacity allows

**Comment by dplsek** [comment]
@jake-costa @ivan-calderon waiting for update from @tomhazledine

**Comment by mark-tate** [comment]
Lungo Goal: no dev work this sprint

**Comment by mark-tate** [comment]
Mocca Goal: have nested steps published to Core

**Comment by mark-tate** [comment]
Red Eye Goal: merged to labs with #2886, feedback from James required

**Comment by bhoppers2008** [comment]
Stepped Tracker moved to labs. Core ticket created by @joshwooding. Closing ticket.
