### ISSUE TITLE
Pill v2 (states: closable/selectable/readonly)

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1873]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [ ] Closable replaced by #2538
- [ ] Selectable pill replaced by #2402
- [ ] Maximum width + truncation replaced by #2539
- [ ] Readonly (site dependency) replaced by #2540
```

**Comment by joshwooding** [comment]
Design work done but dev will be done later

**Comment by joshwooding** [comment]
Created a new ticket to track just design #2248

**Comment by mark-tate** [comment]
is this a dependency for https://github.com/jpmorganchase/salt-ds/issues/1858 ? @bhoppers2008

**Comment by origami-z** [comment]
Replaced with per feature issue
