### ISSUE TITLE
Icon contributions

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1917]
We have had icon requests/contributions from Markets and the FoW experiments team in Bournemouth
- alpha/num sortable
- notification read
- devices e.g. laptop, desktop, mobile
```[tasklist]
### Tasks
- [x] Create new icons
- [x] Add new icons to Figma library as branch
- [x] Check icons with Icon checker plugin
- [ ] Merge Figma library branch
- [x] Export icons as SVGs
- [ ] Add to Github
- [ ] Publish Figma library (internal and community)
```

**Comment by pseys** [comment]
I've created the following: 

- notification-read (outline, solid)
- sortable-alpha (outline only)
- sortable-num (outline only)
- mobile (outline, solid)
- display (outline, solid)
- laptop (outline, solid)
- battery (outline, solid)
- browser (outline, solid)
- devices (outline, solid)
- watch (outline, solid)
- bank (outline, solid)

**Comment by pseys** [comment]
It's been flagged by a team that receipt and receipt-solid are missing from code, but are available in design. We need to add this in at the same time.
