### ISSUE TITLE
Create about section (overview) page

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1923]
Create an About section overview page that links to Roadmap and Research approach, and can be extended to link to more pages in the future.

```[tasklist]
### Tasks
- [ ] Write introductory blurb for top of page
- [ ] Write excerpts for Roadmap & Research approach cards
- [ ] Design illustrations for Roadmap & Research approach cards
- [ ] Add page to site
```

### Background

According to our [target, update IA](https://github.com/jpmorganchase/salt-ds/issues/1483#issuecomment-1544043626), the new [research process page](https://github.com/jpmorganchase/salt-ds/issues/1529) and existing [roadmap page](https://www.saltdesignsystem.com/salt/getting-started/roadmap) should live within a new "About" section:

> * About Salt
>     * What is Salt?
>     * Who is it for?
>     * The Salt ecosystem
>     * **Roadmap**
>     * Releases
>     * Partners
>     * Case studies
>     * **Research approach and methods**
>     * News
>     * Blog
>     * FAQs

However, that necessitates some kind of "About" overview page that you land on when clicking "About" in the main site nav. In keeping with our other sections, it would make sense for this to be a grid of cards linking to the child pages (e.g. "[Getting started (overview)](https://www.saltdesignsystem.com/salt/getting-started/index)" and "[Foundations (overview)](https://www.saltdesignsystem.com/salt/foundations/index)")

**Comment by dplsek** [comment]
07/07 - James reviewing some pr feedback, possibly merged today if not, early next week
