### ISSUE TITLE
Document a11y approach to website

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1945]
We need to finalize and publish Salt's approach to accessibility

```[tasklist]
### Tasks
- [ ] Ensure our approach to accessibility is agreed and written up (eg., parity with predecessor UITK system and aligning to wcag 2.1, and welcoming accessibility contributions from community)
- [ ] Put in place, and link to, contribution channel for accessibility (what channel(s) should we use? what are our recommendations for successful contribution/what would we ideally like?)
- [ ] Publish to the Salt website (need to consider our current and [target IA](https://github.com/jpmorganchase/salt-ds/issues/1483#issuecomment-1544043626) to decide where this should live)
```

**Comment by james-nash** [comment]
On that 2nd point about a11y feedback and contributions, I think we should:

* Direct people to our [existing bug reporting form](https://github.com/jpmorganchase/salt-ds/issues/new?assignees=&labels=type%3A+bug+%F0%9F%AA%B2%2Cstatus%3A+awaiting+triage&projects=&template=bug_report.yml) to report a11y issues in our components (or our site). An a11y bug is a bug like any other, having a separate way of reporting them would just unnecessary confusion or complexity IMHO
* For contributions, I believe we need to define and document our overall contribution process first (which is something we need to do anyway). Once we have that, as with the bugs, the need for a special a11y contribution process might disappear.
    * I do like the suggestion of having an example of what a "good" contribution looks like, so perhaps our general contribution process could include a few examples, one of which would be an a11y-related contribution.

**Comment by joshwooding** [comment]
THis
