### ISSUE TITLE
DSKS series kick-off

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1954]
```[tasklist]
### Tasks
- [x] Agree dates and hosts for first 4 sessions
- [x] Set-up first event in IEMS
- [x] Send out invite for first event
- [x] Prep Tech Tube channel for first recording
- [x] Host first event (18 July)
- [x] Record first event
- [x] Add recording to Tech Tube
- [x] Send attendee lists to @tadxd post session
- [x] @tadxd to field survey
```

Establish design system knowledge share series (DSKS) aimed at designers new to Salt to improve understanding of principles, foundations, components and patterns. Each session will be 60 mins in length and occur every 3-4 weeks.

**Comment by pseys** [comment]
**Event registration link**
https://iems-prod.prod.aws.jpmchase.net/registration/event/5043
