### ISSUE TITLE
Remove all Tertiary tokens

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1961]
```[tasklist]
### Tasks
- [x] Remove tokens from Figma theme file
- [x] Remove from Light mode Figma library
- [x] Remove from Dark mode Figma library
- [x] Publish updated Figma libraries internally
- [x] Publish updated Figma libraries to community
- [ ] Remove from palette
- [ ] Remove from characteristic
```

The following tokens can be removed: 

- container-tertiary-borderColor
- container-tertiary-background
- container-tertiary-borderColor-disabled
- container-tertiary-background-disabled
- palette-neutral-tertiary-border
- palette-neutral-tertiary-background
- palette-neutral-tertiary-border-disabled
- palette-neutral-tertiary-background-disabled
- palette-neutral-tertiary-background-readonly

**Comment by pseys** [comment]
Need to make sure **palette-neutral-tertiary-separator** is left alone, as it's still in use. All other Tertiary tokens can be removed.

**Comment by pseys** [comment]
@bhoppers2008 light and dark mode libraries have been updated and published internally, they just need to be published to the community. The publish description is as follows: 

Updated 11 Jul 2023
All container-tertiary tokens removed as they are no longer in use.

**Comment by bhoppers2008** [comment]
> @bhoppers2008 light and dark mode libraries have been updated and published internally, they just need to be published to the community. The publish description is as follows:
> 
> Updated 11 Jul 2023 All container-tertiary tokens removed as they are no longer in use.

Done.

**Comment by libertymayc** [comment]
closing, captured in https://github.com/jpmorganchase/salt-ds/issues/2000
