### ISSUE TITLE
Usability Testing | Component_Stepped Tracker

### ISSUE THREAD

**Issue by tadxd** [jpmorganchase/salt-ds#1975]
Evaluate the usability of components early in the development process and provide recommendations to inform design iterations. Two tests: (1) expectancy; (2) usability in practice. Rinse and repeat effort across critical components. 
```[tasklist]
### Tasks
- [x] Stepped Tracker - get design prototype into UZ
- [x] Stepped Tracker - field and analyze results from UT
- [x] Stepped Tracker - report findings
```

```[tasklist]
### Deliverables
- [x] Results report on Stepped Tracker UT
```

**Comment by parsakhan21** [comment]
Aug 2 - meet ivan to talk through stepped tracker today

**Comment by tadxd** [comment]
Aug 25 - stepped tracker next up; awaiting slight mod on component in pattern test - need Ivan support.

**Comment by parsakhan21** [comment]
Aug 30 - stepped tracker is live

**Comment by tadxd** [comment]
Sep 1 - Stepped Tracker done. Sharing results with lead designer + team
