### ISSUE TITLE
MTK icon contribution

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1988]
```[tasklist]
### Tasks
- [x] Review icon contribution
- [x] Confirm changes (if any)
- [x] Add icon to Figma library
- [ ] Publish icon library upate to internal Figma
- [ ] Publish icon library update to Figma community
- [ ] Add SVG icon to Github
```

The following icons have been contributed to the icon-set: 

- Weight
- Sort size ascending
- Sort size descending

Due to the addition of the weight icon I have also designed a 'scales' icon to accompany it.

**Comment by pseys** [comment]
Added: 
- Weight; solid and outline
- Scales; solid and outline

**Comment by parsakhan21** [comment]
July 24 - design - ready; if dev has time, add it in

**Comment by libertymayc** [comment]
jul 25 - https://github.com/jpmorganchase/salt-ds/pull/2052
