### ISSUE TITLE
Remove Taggable Characteristic

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2014]
```[tasklist]
### Tasks
- [x] Remove Taggable from Theme figma file
- [x] Remove from Light mode palette in Figma
- [x] Remove from Dark mode palette in Figma
- [x] Publish updated palettes to internal Figma users
- [x] Publish updated palettes to Figma community
- [x] Deprecate characteristic and tokens in code
```

**Comment by parsakhan21** [comment]
July 19 - back of pill work, add read only state for pill

**Comment by bhoppers2008** [comment]
> @bhoppers2008 to publish changes to Figma community

Published.

**Comment by parsakhan21** [comment]
July 24 - done in design

**Comment by pseys** [comment]
Pill will need to be updated to match the design spec before Taggable can be deprecated.
