### ISSUE TITLE
Add --actionable-primary-background-readonly

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2015]
```[tasklist]
### Tasks
- [x] Add characteristic and palette token to Theme file in Figma
- [x] Add token to Light mode palette in Figma
- [x] Add token to Dark mode palette in Figma
- [x] Publish palette updates to internal Figma users
- [ ] Publish palette updates to Figma community
- [ ] Add tokens in code
```

Need to add the following: 

**Characteristic (Actionable)**
--actionable-primary-background-readonly
--actionable-cursor-readonly

**Palette (Interact)**
--palette-interact-primary-background-readonly

**Comment by pseys** [comment]
Files have been updated. There's an open question with @bhoppers2008 regarding opacity levels and the changes will need to be published to Figma community.

**Comment by bhoppers2008** [comment]
@pseys have replied to the figma comment but not totally sure what you mean. Can you reply :)

Does it need publishing to the community regardless of that answer?

**Comment by parsakhan21** [comment]
hi all, following up on this issue - can we please address ben's question/comments above? @pseys

**Comment by bhoppers2008** [comment]
Done.

**Comment by pseys** [comment]
@ZarkoPernar @libertymayc @joshwooding could one of you refresh my memory on this one. We had a task to add 3 tokens, but they're not in code and this issue is closed. Did we decide not to add them in the end? They're in design but this looks like a mistake, so I can remove them if needs be.

**Comment by libertymayc** [comment]
I believe this was for selectable Pill which wasn't added in Pill v1? and then the issue was closed as we were going to collect all things needed for dev work in the sheet
