### ISSUE TITLE
Salt AG-Grid theme supports v29+ ag grid

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2103]
Currently ag grid is using [Legacy SASS](https://www.ag-grid.com/react-data-grid/global-style-customisation-sass-legacy/) method to generate CSS, and need to move to [new way](https://www.ag-grid.com/react-data-grid/global-style-customisation-sass/).

Also new versions of ag grid introduced proper CSS like below
```css
[class*=ag-theme-] {
   ...
    --ag-background-color: #fff;
   ...
}
```
These will override Salt colors applied, so will need to follow new way of overriding colors.

[StackBlitz Demo](https://stackblitz.com/edit/salt-ag-grid-theme-v30-bug?file=App.jsx) of ag grid v30 CSS variable breaking styling.

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2557
- [x] Consolidate existing class attribute matching and mixin approach
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2602
- [x] Snapshot release and test
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2531
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2683
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2792
- [x] Add test for #3127
- [x] Menu list style different between filter panel and column panel
- [x] Regression of #3084
- [x] Regression of #3065
- [x] Possible regression of #2906
- [x] [v31] Side panel incorrect fixed width. Possible fix: `.ag-tool-panel-wrapper > .ag-react-container` to inherit
- [x] [v31] cell range selection color incorrect
- [x] [v31] floating filters incorrect additional half border on the right
- [x] [v31] status bar misaligned verticially
- [ ] ~~Make it possible to import density / mode specific css entry~~ Not needed given bundle size no longer a concern
- [x] Minimize production css bundle
- [x] Update default style in `package.json` to salt one
```

**Comment by joshwooding** [comment]
You beat me to creating this, we've already discussed the next set of actions, and moving to the new CSS approach is part of it

**Comment by origami-z** [comment]
Updated release date, as work has not started.

**Comment by origami-z** [comment]
update target date to match subtask

**Comment by origami-z** [comment]
23 Oct - cypress snapshot test merged to next branch. Fixing conflict from main, will continue feedback afterwards.

**Comment by joshwooding** [comment]
Moved the target date to 31st Oct to accommodate feedback from consumers

**Comment by joshwooding** [comment]
Hard-coded colours need to be removed and mapped to Salt colours.

**Comment by origami-z** [comment]
3 Nov - PR ready for review, moving to feedback stage

**Comment by shey-v** [comment]
6 Nov - PR reviews and waiting for more to be able to merge. @joshwooding

**Comment by joshwooding** [comment]
Almost ready, creating tests for UITK theme. Consumers not able to test the theme yet as they haven't begun their upgrade.

**Comment by origami-z** [comment]
13 Nov - PR review requested this morning, Chromaticc tests added for uItk theme

**Comment by origami-z** [comment]
20 Nov - wip, more test to be fixed. ETA tmr

**Comment by origami-z** [comment]
22 Nov - dev done. verifying test passing, review for dev & design review (both Salt and UITK theme).

**Comment by origami-z** [comment]
24 Nov - snapshot tests pass. Range selection bug raised. Can't merge to main, bug fixes needed for v1.

**Comment by origami-z** [comment]
27 Nov - doc changes on ag grid next branch.

**Comment by origami-z** [comment]
1 Dec - trying at snapshot (help from @lukeac123), at feedback stage.

**Comment by origami-z** [comment]
6 Dec - more tests to be added for range selection. discuss how to manage 2 ag grid theme version.

**Comment by origami-z** [comment]
8 Dec - Need additional icon (drag and drop row, GH issue? @pseys did it). Version management to be discussed.

**Comment by origami-z** [comment]
11 Dec - icons created, needs to be added to the icon font (how? to be confirmed). Version management to be discussed.

**Comment by joshwooding** [comment]
18 Dec - Icons have been merged, and the data grid theme has been updated with the new icons.

**Comment by origami-z** [comment]
Closed by #3195
