### ISSUE TITLE
AG Grid Roadmap

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2104]
Our current plan is:

1. Fix issues raised by consumers and add support for HD compact

```[tasklist]
### Bugs
- [ ] #2053
- [ ] #2088 
- [ ] #2080 
- [ ] #2081 
- [ ] #2082 
- [ ] #2083 
- [ ] #2074 
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2079
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2185
- [ ] #2258 
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2479
```

```[tasklist]
### Tasks
- [ ] #1843
```

2. Stop supporting UITK version of AG Grid theme and move Salt AG Grid theme to CSS variables.

This will be either a v2 of the ag-grid-theme or a new theme labelled next. This will probably happen in late Q3

```[tasklist]
### Tasks
- [ ] #2103
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2792
```
