### ISSUE TITLE
Create new token for 'size-indicator'

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2121]
Within the Nav item component, there is a requirement to add in a new token. 

@pseys  and @libertymayc  discussed last week and agreed a token would be worth adding. "It allows us to treat indicators and accent bars differently (or potentially remove the latter in the future) without having to divide or multiple too many tokens". 

Therefore, we need a new token called 'size-indicator' which is 1px in HD, 2px in MD, 3px in LD and 4px in TD. 
```[tasklist]
### Tasks
- [x] Add --salt-size-indicator to Figma theme file
- [x] Add --salt-size-indicator to code
- [x] Add size-indicator to website Foundations documentation including basic description
```

**Comment by shey-v** [comment]
cc @JoanaMMoreira to add the token to code. fyi @libertymayc
