### ISSUE TITLE
Add Notation text style

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2124]
```[tasklist]
### Tasks
- [x] Remove typography attributes from Accent
- [x] Add Accent typography attributes to Text characteristic and call 'notation'
- [x] Add 'notation' to Typography style library in Figma
- [ ] Add 'notation' to websites Foundation docs
- [x] Add notation in code
```

All typography styles have been removed from Characteristics and groups in the Text characteristic with the exception of Accent. The accent styles are needed for more components so needs to be added to Text. This also simplifies the token structure and means the styles can be made available in Figma.

**Comment by pseys** [comment]
Typography Foundation still needs updating.

**Comment by joshwooding** [comment]
To be done as part of #4057
