### ISSUE TITLE
Update Input read-only state

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2179]
### Description
The current Salt Input has the following attributes in a read-only state:

- No padding-left/-right
- Is not focusable.

This was a decision based on design exploration and ADA SME feedback from the ETF Instruct team. However, the decision causes alignment issues and is difficult to justify to the teams that query the decision.

As a result, this issue will:

- Add spacing-100 padding to left and right of Input in read-only state.
- Allow read-only state to be focusable by default.

These changes will apply to Input and any dependant/ or related components, including:

- Input
- Combo Box (dependant)
- Multiline (related)
- Dropdown (dependant)

### Tasks
- [ ] Update Input code 
- [ ] Update Multiline code @libertymayc 
- [ ] Align Combo Box code @Fercas123 
- [ ] Align Dropdown code @feliciackh 
- [ ] Update all Figma specs @bhoppers2008 
- [ ] Update all Figma components @bhoppers2008

**Comment by libertymayc** [comment]
"Allow read-only state to be focusable by default."
Do we want to add a prop to make it optionally not focusable?

**Comment by libertymayc** [comment]
added also for CB/RB @joshwooding

**Comment by joshwooding** [comment]
> added also for CB/RB but its not in the description - just checking that was intended? @joshwooding @bhoppers2008

The behaviour should be consistent across controls
