### ISSUE TITLE
Remove --salt-zIndex-docked from Z-Index Foundation

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2183]
Following a discussion with @origami-z @bhoppers2008 @joshwooding we believe Docked is no longer needed as it relates to a legacy feature within UITK and isn't something we're planning on recreating within Salt (relates to the Drawer component). 

```[tasklist]
### Tasks
- [x] Remove Docked from Figma doc
- [ ] Remove Docked from Z-Index Foundation page on website
- [ ] Deprecate Docked token from code
- [ ] Add to v2 removal list
```
