### ISSUE TITLE
Change --salt-palette-neutral-backdrop value

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2190]
In light mode change `--salt-palette-neutral-backdrop` value from `--color-black` to `color-white`

```[tasklist]
### Tasks
- [x] Change value in Figma docs
- [x] Change value in Light mode figma library
- [x] Change in code
```

**Comment by mark-tate** [comment]
How do we communicate theme changes like this so we can correlate code and figma specs together ?

**Comment by pseys** [comment]
This has been resolved as part of #2571
