### ISSUE TITLE
Add --salt-size-discrete to Foundations

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2255]
Token needed to accommodate Badge, Tooltip and Overlay 'sharktooth', and replace --salt-size-selectable to ensure only one token is required. 

```[tasklist]
### Tasks
- [ ] Add --salt-size-discrete to Foundation
- [x] Add --salt-size-discrete to Figma theme doc
- [ ] Depricate --salt-size-selectable in Foundation
- [x] Remove --salt-size-selectable from Figma theme doc
```
