### ISSUE TITLE
Change Badge to use --salt-size-discrete 

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2256]
In order for Badge to be center-aligned vertically within Navigation item etc. it needs to follow the even-number ramp provided by the new size token `--salt-size-discrete`

```[tasklist]
### Tasks
- [ ] Change size of Badge in Figma libraries
- [ ] Notify all designers of change in order for other components to be updated
- [ ] Change size of Badge in code
```

**Comment by pseys** [comment]
New token changed from `--salt-size-detail` to `--salt-size-descrete` to avoid confusion with previously deprecated tokens with the same name but different values.
