### ISSUE TITLE
Migration and Support | Case Studies 

### ISSUE THREAD

**Issue by tadxd** [jpmorganchase/salt-ds#2339]
Case studies with initial adopters of Salt to showcase experience and value prop of the design system. 

```[tasklist]
### Tasks
- [x] Determine teams to speak to -- end Sep (MB)
- [x] Determine what design/dev want in case study and internal/external -- end Sep (MB)
- [x] Finalize interview protocol -- mid Oct
- [ ] Schedule and hold interviews -- end Oct / early Nov
- [ ] Analysis and Reporting -- early Nov
```

**Comment by joshwooding** [comment]
working with @mikearildbrown to get feedback on what devs and designers need

**Comment by joshwooding** [comment]
@tadxd meeting with @mikearildbrown tomorrow

**Comment by origami-z** [comment]
16 Oct - to be follow with different contacts

**Comment by origami-z** [comment]
23 Oct - park and focus on design orientated
