### ISSUE TITLE
Add Form Field support to Dropdown

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2359]
## Description
The dropdown should support being nested inside Form Field.

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
```[tasklist]
### Code Tasks
- [ ] Hook up ARIA attributes, cy test
- [ ] Validation status, chromatic test
```

**Comment by mark-tate** [comment]
Hold off picking this up, until we have a discussion on the next steps for List based components

**Comment by origami-z** [comment]
Remove priority label, as no one will pick this up anytime soon.

**Comment by joshwooding** [comment]
Closed #3131
