### ISSUE TITLE
Splitter Design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2383]
## Description   
Describe the pattern 

## Context   
Describe scenarios where the pattern is most applicable 

## Extra information  
UITK Splitter docs can be found [here](https://uitk.gaiacloud.jpmchase.net/build/components/splitter).
Salt Splitter could make use of a third party library.
Consider if Salt Splitter should be compatible with Salt layout components (Border layout/ Parent Child layout/ etc).

Need to work with desktop / multi-window environment (e.g. used in a desktop Dialog)

```[tasklist]
### Tasks
- [ ] Check the issues with LOB to confirm the feasibility
- [ ] Check with DP desktop designs / any advice
- [ ] Decide Design token (check with Darrin/Nav)
- [ ] Design Characteristic Spec
- [ ] Design Figma components in Light/Dark
- [ ] Migration doc
- [x] Add new design tokens to Salt Next Styles library
- [ ] Add new design tokens to Salt Light mode library
- [ ] Add new design tokens to Salt Dark mode library
- [ ] Add new design tokens to Salt Theme Characteristics Figma file
```

**Comment by joshwooding** [comment]
TODO: investigate https://github.com/bvaughn/react-resizable-panels

**Comment by mark-tate** [comment]
Zazu Goal: M(5)
- define token/characteristics
- ready for dev by EOS

**Comment by mark-tate** [comment]
Goal: finalise site examples (already ready for dev)

**Comment by shey-v** [comment]
- Site docs / examples being refined based on convo today with Zhihao
- Tokens being added by Paul today to Salt 1 & 2 libraries
- Shey working on finalizing Figma component (once tokens have been added to library)
- Shey working on Figma guide

**Comment by pseys** [comment]
The following tokens need to be created. I've added them as variables within the Salt Next Style library in Figma (to be published).

| Characteristic | Palette | Light | Dark |
| --- | --- | --- | --- |
| `--salt-separable-foreground` | `--palette-foreground-primary` | `black` | `white` |
| `--salt-separable-background` | `--palette-alpha-none` | `transparent` | `transparent` |
| `--salt-separable-foreground-hover` | `--palette-foreground-primary` | `black` | `white` |
| `--salt-separable-background-hover` | `--palette-alpha-weak` | `black A15%` | `white A15%` |
| `--salt-separable-foreground-active` | `--palette-foreground-primary-alt` | `white` | `white` |
| `--salt-separable-background-active` | `--palette-accent` | `blue-500 / teal-500` | `blue-500 / teal-500` |

The following token needs to be created. I've added it into the variables within Salt Next Style Library (to be published).

| Foundation | High | Medium | Low | Touch | 
| --- | --- | --- | --- | --- |
| `--size-border-stronger` | `4px` | `4px` | `4px` | `4px` |

**Comment by pseys** [comment]
Salt (Next) Styles library update published in Figma.

**Comment by shey-v** [comment]
- Site docs / examples ready for dev
- Added (Salt 1 & Next) in branch, Figma guide and QA in progress
- Working on accessibility spec

**Comment by shey-v** [comment]
- Under final design review

**Comment by shey-v** [comment]
- Addressing feedback from Ben after design review
- Have merged Figma component to Salt Next and Salt Current libraries (component will stay hidden until the build is completed)

**Comment by shey-v** [comment]
- Feedback from Ben has been addressed and the spec + site docs are in a 'ready for dev' state. 
- Few unknowns on implementation approach until build has begun (agreement with Josh/Zhihao to tweak + update specs or docs once the implementation has begun).
