### ISSUE TITLE
Tabs: Add main and inline tabs aligned to Salt design language and update tokens

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2389]
## Description
Tabs should come in two variants — main and inline — to be used below app header or within the content area.

https://www.figma.com/file/wh4iwNOuVIpebbV1qgSnxP/Tabs-2?type=design&node-id=1%3A52295&mode=design&t=Bt2YNVF3eoRAhyZZ-1

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2604
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2587
```

**Comment by JoanaMMoreira** [comment]
@dplsek here's the storybook link for you to review please: https://dcdd9be4.saltdesignsystem-storybook.pages.dev/?path=/story/lab-tabs-next-tabstrip-next--default
