### ISSUE TITLE
Realign Stepped Tracker to design language

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2395]
```[tasklist]
### Features
- [ ] Tokens applied to component from theme need to be updated to more appropriate selection.
```
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
