### ISSUE TITLE
Add multi-select to combo box

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2413]
## Description
Overlay list displays a multi-select list component. 
On selection from the list, items are added to the field as pills.
The field vertically expands as options are added to the pill group.
Pills can be removed from the field by clicking their close buttons.
The field displays a close button when options are added. Clicking the close button removes the entire selection.
Pills have a maximum width, with truncated values, which is configurable. Pills should never extend beyond the width of the field. 
The overlay list displays all options when open, with selected options demarcated by the list item checkbox.
More details can be found in UITK multiple select Combo Box docs.
This component has a dependency on a closeable pill & multiselect list.

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
```[tasklist]
### Dependencies
- [ ] #2541
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2388
```
