### ISSUE TITLE
Create component for single date picker

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2416]
## Description
TBD.

## Tasks

```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] Fill (Primary, Secondary, Tertiary)
- [x] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [x] Controlled API
- [x] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] In Code & Figma (Component + Guide)
- [x] Supporting site documentation
```
```[tasklist]
### Dependencies
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2415
```
