### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2427]
## Description
TBD.

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
- [ ] Single-level menus
- [ ] Multi-level menus
- [ ] Menu groups
- [ ] Separator
```

**Comment by origami-z** [comment]
27 Nov - Adjusting dates, @shey-v is on another task

**Comment by origami-z** [comment]
modify start date, delayed by other tasks

**Comment by origami-z** [comment]
8 Dec - Kick off yesterday, audit on feature request on menu families, aiming to lock down scope mid next week

**Comment by shey-v** [comment]
15 - Dec - scope agreed (needs some refinement) + design started

**Comment by joshwooding** [comment]
18 Dec - on track, will be delivered in the new year.

**Comment by joshwooding** [comment]
09/01 - Working on ADA spec, had quick design review earlier today. Ready for implementation

**Comment by shey-v** [comment]
22/01 - Component in review, Figma guide is being created today, site docs need to be reviewed by @jpmorganchase/salt-content. Dev work about to start.

**Comment by shey-v** [comment]
23/01 - Figma assets ready for review @bhoppers2008 
[Figma component guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/aDVL1IJNUgZAy0CZvsC8Ez/Salt-Figma-Component-Guides?type=design&node-id=3833%3A967&mode=design&t=WcJfUcDSBvMUmJ7y-1)
[Dark components](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/mrsufFgACck618gnIBiRH5/Salt-Dark-Components?type=design&node-id=7817%3A910&mode=design&t=JQlszj9jgdn1Teqh-1)
[Light components](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/v8MO7mzKgXxzMamDZIY3Fw/Salt-Light-Components?type=design&node-id=14177%3A1107&mode=design&t=ZEuEnXzts6i493f0-1)
[
Menu site docs](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/Shared%20Documents/General/Salt/Component%20Docs/[Menu.docx](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/Shared%20Documents/General/Salt/Component%20Docs/Menu.docx?d=wa334187e625141238a920e5f203ee667&csf=1&web=1&e=d3fBNy)?d=wa334187e625141238a920e5f203ee667&csf=1&web=1&e=d3fBNy) are being reviewed by @mikearildbrown

**Comment by joshwooding** [comment]
POC: https://github.com/jpmorganchase/salt-ds/compare/main...menu

cc @alycrys

**Comment by mark-tate** [comment]
available from Core
https://www.saltdesignsystem.com/salt/components/menu/examples
