### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2437]
## Description
TBD.

## Tasks

```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

**Comment by shinytoyrobots** [comment]
Carousels are bad patterns - I don't think this is something that we should define or build, as doing so puts a design system approval on a fundamentally flawed UX.

**Comment by origami-z** [comment]
Bump to Q3, need more tech consideration before publish examples

**Comment by mark-tate** [comment]
Assume it depends on Deck layout  [#2448](https://github.com/jpmorganchase/salt-ds/issues/2448)

**Comment by bhoppers2008** [comment]
Needs discussion about whether carousel is a component or pattern. Related to #368

**Comment by mark-tate** [comment]
Tecno Goal: kickoff for this sprint

Decide whether a component or a pattern
Review Pepper

**Comment by mark-tate** [comment]
Refactoring into a composable solution 
Technical approach to be agreed by EOS, minimum design to be agreed by EOS

**Comment by mark-tate** [comment]
Oregano Goal
Publish pattern by EOS

**Comment by mark-tate** [comment]
catchup today to align the design with the implementation

**Comment by mark-tate** [comment]
Ontrack
- rescoped, ticket to be updated.

**Comment by joshwooding** [comment]
@Fercas123 investigating a bug around resizing, tests have been written and @jake-costa has given feedback. Meeting later to go over the rest of the feedback.

**Comment by mark-tate** [comment]
ontrack

**Comment by jake-costa** [comment]
Meeting on Feb 26 to discuss:
screen reader announcement after Previous/Next button is pressed
dragging/scrolling for mobile
Focus indicator cutoff on button

@Fercas123

**Comment by mark-tate** [comment]
Paprika: Labs by end of wk1
targetting core by end of Q1
Site documentation to be published in Paprika

**Comment by mark-tate** [comment]
Labs version to be reviewed by EOS

**Comment by mark-tate** [comment]
in PR

**Comment by mark-tate** [comment]
Review for merge to Labs ?
Cardoman Goal: Core decision in next sprint.

**Comment by mark-tate** [comment]
Clove Goals:  reviewed by stakeholders
1. interactive content example to be added
2. hotspots over images
3. title placement (left and right options)
4. Draggable (may come as a second iteration)
5. Light box (what types of images can be put in there)

Review above and understand what we can do now (through docs) and what needs to be a follow up iteration.

**Comment by Fercas123** [comment]
interactive content example to be added - WIP
title placement (left and right options) - TBD (@ivan-calderon we should discuss this possibility)

hotspots over images -  https://github.com/jpmorganchase/salt-ds/issues/5045
Draggable - https://github.com/jpmorganchase/salt-ds/issues/5031
Light box - https://github.com/jpmorganchase/salt-ds/issues/5030

**Comment by origami-z** [comment]
May 1 - updates to examples WIP

**Comment by origami-z** [comment]
MTK feedback

Issue 1

From carousel -> zoomed carousel, the index is correct. But from zoomed carousel -> carousel, the index always reverts back to the previous state. NOTE - this revert does not happen when you click outside to close the dialog. It only happens when you click the X button to close the Carousel.

Issue 2

Some cards jump to the right by 1px which means the right border is not visible on those cards. You can see the issue happening in the same gif as issue 1 (notice the absence of the right border in slide 2 and slide 4).

**Comment by Fercas123** [comment]
investigating issue, reproducible example: https://stackblitz.com/edit/salt-test-question-wajfxhet?file=package.json,App.tsx

**Comment by ivan-calderon** [comment]
[Carousel build QA](https://www.figma.com/design/W2Qn8LUGPmCSWVyC8AVvFm/Carousel--DS-?node-id=453-929&t=oV3kxCCl8DhUc1IH-1) review shared. Details to discussed.

**Comment by mark-tate** [comment]
Last release of Lab version will be Mace
Aiming for Core in Cinnamon, subject to any feedback of Mace release

**Comment by mark-tate** [comment]
Merging to Labs in Cinnamon, will be pushed to Core in  Fenugreek
