### ISSUE TITLE
Add range support to date picker

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2454]
## Description
The Date picker should allow ranges of dates to be picked

## Tasks

```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] Fill (Primary, Secondary, Tertiary)
- [x] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [x] Controlled API
- [x] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] In Code & Figma (Component + Guide)
- [x] Supporting site documentation
```
