### ISSUE TITLE
Component Docs—Second Round of Edits

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2463]
Content team to complete a second round of edits to ensure consistency across the documents in both style and definition.

```[tasklist]
### Tasks
- [x] Send over component docs for third-party proofreading
- [x] Receive proofread component docs
- [x] Compile a report on proofreaders' common notes and issues
- [x] Update the component doc guidelines and definition guidelines
- [x] Share relevant guidelines with the wider team through Confluence
- [x] Create a branch to update the existing component docs
- [x] Update every existing component doc to ensure compliance with the newly-agreed guidelines and proofreading feedback
- [ ] Create a pull request for the branch
- [ ] Merge!
```

```[tasklist]
### Component docs updated in branch—box ticked when doc complies with both proofreading feedback AND new guidelines
- [x] accordion
- [x] avatar
- [x] badge
- [x] banner
- [x] border layout
- [x] button
- [x] card
- [x] checkbox
- [x] combo box
- [x] country symbol
- [x] dialog
- [x] drawer
- [x] dropdown
- [x] flex layout
- [x] flow layout
- [x] form field
- [x] grid layout
- [x] icon
- [x] input
- [x] link
- [x] list
- [x] multiline input
- [x] panel
- [x] pill
- [x] progress
- [x] radio button
- [x] salt provider
- [x] spinner
- [x] stack layout
- [x] status indicator
- [x] switch
- [x] text
- [x] toast
- [x] toggle button
- [x] tooltip
```
