### ISSUE TITLE
Component site index page—improve "lab" visibility

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2502]
Unclear which components are in lab. If we improve visibility, and once all other component docs are out of Storybook, we can consider removing the "available and upcoming components" table.

```[tasklist]
### Tasks
- [ ] Add 🚧 symbol to navigation link titles for lab components
- [ ] Change nav link sort so lab components appear at the bottom of the vertical nav list
- [ ] Add "in progress" badge to lab component doc pages
- [ ] Add explanatory copy to index page
```

**Comment by JoanaMMoreira** [comment]
> @lilyvc below is proposed explanatory copy for the index page, also checked by Delme.
> 
> > Stable components do not feature an accompanying symbol in their navigation link titles. You can find them in the `@salt-ds/core` package.
> > Unstable components feature a 🚧 symbol in their navigation link titles. These are under active development and may not function as expected. You can find them in the `@salt-ds/lab` package.

@mikearildbrown is this meant to replace all the copy above the components table?

**Comment by JoanaMMoreira** [comment]
I've raised this PR https://github.com/jpmorganchase/salt-ds/pull/2503 but let me know if the copy should be amended as per the comment above
