### ISSUE TITLE
Add AG Grid Theme documentation to site

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2506]
AG Grid Theme is one of the last remaining Storybook component docs on the site. Once we've ported this to the new format, we can consider removing the table from the component docs index page.

```[tasklist]
### Tasks
- [x] @mikearildbrown to share a branch w/ draft MDX files based on the Storybook docs and make changes where necessary
- [ ] @libertymayc to correct any technical points/issues/changes needed
- [ ] @libertymayc to port examples to new format (if applicable)
- [ ] @mikearildbrown to send to proofreaders for final checks
- [ ] @mikearildbrown to make final copy edits and start a pull request.
```

**Comment by libertymayc** [comment]
@mikearildbrown I assumed we would only move over the Salt theme rather than the old one?
will look at the other bits when I get the chance today

**Comment by libertymayc** [comment]
as discussed in stand up, will not be including old theme - only salt will be on site

@mikearildbrown I merged your branch into mine, so the changes can be made in the PR directly #2533
