### ISSUE TITLE
Figma theme library corrections

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2518]
The following styles are available in the Figma light and dark mode libraries but are not used in code and are no longer required.

- Remove navigable-background from Figma libraries
- Remove navigable-background-active from Figma libraries
- Remove -actionable-primary-background-readOnly

```[tasklist]
### Tasks
- [x] Remove styles from light mode library
- [x] Remove styles from light mode library
- [x] Publish internally
- [x] Publish externally
- [x] Update Figma theme file
```
