### ISSUE TITLE
Spinner v2

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2529]
Details to be filled by @dplsek 
```[tasklist]
### Tasks
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
```

```[tasklist]
### Deliverables
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2590
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2591
```

```[tasklist]
### Features
```

**Comment by lilyvc** [comment]
I would probably change the status of this to amber (not sure if I can?) because we've had to go back to design to figure out how to make the changes without breaking what is currently in core.
