### ISSUE TITLE
Tokenized Input

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2541]
## Description

only grows when adding more pills (not shrinking down to 1 line when out of focus)

Reviews stakeholder feedback of early version to see if still an issue.
https://github.com/jpmorganchase/salt-ds/issues/3024

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
```[tasklist]
### Dependencies
- [ ] #2538
- [ ] #2539
```

**Comment by origami-z** [comment]
18 Oct - Removed from release plan due to dependency of Pill

**Comment by origami-z** [comment]
13 Nov - picking up again, starting from previous design spec

**Comment by Fercas123** [comment]
- POC review planned for TI on 16/11,
- [Ongoing conversations about input adornments](https://github.com/jpmorganchase/salt-ds/pull/2720#issuecomment-1810937978) will fix some issues with pill inside MLI 
- [MinWidth change required in pillNext ](https://github.com/jpmorganchase/salt-ds/issues/2728)

**Comment by origami-z** [comment]
17 Nov - POC dev meeting yesterday. Updated some implementation , no blocker, to check whether Multiline is needed or not.

**Comment by origami-z** [comment]
20 Nov - working on styles & types. Most func done. Aiming for review on Wednesday. No blockers.

**Comment by origami-z** [comment]
22 Nov - did some tweak based on feedback, aiming for dev review tomorrow, tests to be written. Moving to amber.

**Comment by Fercas123** [comment]
Questions looking to be resolved in KO/conversation on 27/11:
- should input have height 100%
- hover on highlighted
- pills gap
- close button height, on pill or TI?
- TI Next, or should we modify types in deprecated usages
- tab navigation currently focuses close buttons in pill.

**Comment by origami-z** [comment]
4 Dec - same as above

**Comment by origami-z** [comment]
6 Dec - design & dev review needed

**Comment by origami-z** [comment]
8 Dec - pending review

**Comment by origami-z** [comment]
11 Dec - Review pending

**Comment by joshwooding** [comment]
18 Dec - Updated the docs, ready for reviews. Confident about getting this across the line. @dplsek to take a look at the design review

**Comment by joshwooding** [comment]
20 Dec - Had a review session with @bhoppers2008 @dplsek

**Comment by joshwooding** [comment]
09/01 - Addressed feedback, reading for review. Need to discuss the Pill work #2871

**Comment by Fercas123** [comment]
17/01 - merged to Labs, ready for 'Core' review

**Comment by mark-tate** [comment]
As of Q2, we don't have a use-case for this, it was previously thought we needed this for ComboBox but we decided against creating it as a standalone component and composed the functionality within ComboBox instead.

If you have a use-case that requires a standalone Tokenized Input then let us know.
You can create a TokenizedInput (Input + Pill) yourselves but be advised that accessibility support, particulary around keyboard/focus needs some consideration. Potentially a good contribution, once a standalone use-case is clear, talk to us first though, through this issue.

Parking in Q3 for now.

**Comment by mark-tate** [comment]
Moving to Q4 until a use-case surfaces

**Comment by origami-z** [comment]
Sourcegraph search reveals at least 189 `<TokenizedInput` usages .

User reported #3024 as well.

**Comment by origami-z** [comment]
From yesterday's office hour (request by D648918): with below code, try resize the textarea using native handle after pasting in multiple entries. Pills will be re-arranged and last row of pill will be positioned apart from the rest of pills, given textarea / input area is taller than one row of pills

``` javascript
<TokenizedInput
                  expanded
                  data-testid='templates-input'
                  style={{
                    minHeight: '6vh',
                    minWidth: '23em',
                  }}
                  textAreaProps={{ rows: 1, style: {resize: 'both'} }}
                  selectedItems={selectedTemplates}
                  disabled={readOnly}
                  delimiters={[',', '|', '\n']}
                  onChange={(_event, selectedItems: unknown[] | undefined) => {
                    setSelectedTemplates(selectedItems as string[]);
                  }}
                />
```

Additionally, here is a list of suggested props we think could improve the DX for the component:
- `multilineInput` – This should make the tokenizedInputNext look like a multilineInput component.
- `bordered`  –  adds a border, should behave like the bordered prop from multilineInput.
- `direction` – This should define the direction of the pills, prop values: column, row, wrap. Default to wrap.

Example:
``` javascript
<TokenizedInputNext
expanded
selectedItems={listOfSelectedItems}
delimeters={listOfDelimeters}
onChange={handleChange}
multilineInput
bordered
/>
```

**Comment by origami-z** [comment]
Moved to Q1

**Comment by origami-z** [comment]
SO 94438, needing access to `PillProps` to achieve drag and drop to reorder pills

**Comment by bhoppers2008** [comment]
Planned for work in Q2.

**Comment by joshwooding** [comment]
We still need better requirements from Teams on when this component will be used.

**Comment by mark-tate** [comment]
Related to ComboBox iteration, so may not be released as a component.

**Comment by mark-tate** [comment]
To our knowledge all uses of TokenizedInput could be solved using the ComboBox.
A second iteration of ComboBox will be planned.

**Comment by bhoppers2008** [comment]
Migrated to Jira.
