### ISSUE TITLE
Move switch from lab to core

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2550]
Highest bucket of components needed by partnership
```[tasklist]
### Tasks
- [ ] Add all densities and modes to Chromatic
- [ ] Move code, stories, tests
- [ ] Move site docs, remove 🚧, "in progress"
- [ ] Fix all linting issue
```

**Comment by origami-z** [comment]
Extending target date to next week, switch has a few more visual regressions need to be fixed

**Comment by origami-z** [comment]
25 Oct - Depedency Mosaic switch core

**Comment by origami-z** [comment]
done in #2629
