### ISSUE TITLE
Update states in navigation item

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2575]
The navigation item needs more affordance based on recent consumer feedback. 
New blur-active state now has indicator for more affordance and all active states have body strong text treatment.

```[tasklist]
### Tasks
- [x] Shey to update Figma component specs and branch in main libraries.
- [x] Jo to update component in code.
- [x] Shey to review PR.
- [x] Jo to merge and get released.
- [ ] Ben to merge Figma component changes to main library.
```

**Comment by origami-z** [comment]
16 Oct - PR merged last week. Figma component pending review, pending release later this week.
