### ISSUE TITLE
UITK to Salt migration guide v2

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2581]
Continue development of the UITK to Salt internal migration guide.

- Column Layout - ready for content review
- Aria Announcer - ready for content review
- Dialog - ready for content review
- Panel - ready for content review
- Tooltip - ready for content review
- Button Bar - will work on the Button Bar issue first so there is actually some guidance (part of #2380)

```[tasklist]
### Tasks
- [x] Agree the next six components to include at the 13/10 meet
- [ ] Write up guides for the next six components
- [x] Add a frequently asked questions section to UITK site
- [ ] ~~(Possible) add a top banner as the current page looks a bit sparse— @shey-v thoughts?~~
```

**Comment by mark-tate** [comment]
we should aim to deliver something for each of these components by the 20th

@mikearildbrown can iterate back on this later (if required)

**Comment by lilyvc** [comment]
Just to confirm, there are 6 components in this list, not 10 as suggested by the tasks?

**Comment by origami-z** [comment]
23 Oct - SO done, except Button Bar waiting pattern page. Site Dev review pending

**Comment by joshwooding** [comment]
Only FAQ left, aim to release by end of tomorrow
