### ISSUE TITLE
Progress: Supporting site documentation

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2586]
```[tasklist]
### Tasks
- [ ] Designer and developer work on site doc in word template
- [ ] Contnet team to review
- [ ] When all reviews complete, developer uploads to the site
- [ ] Design and content check documentation on site - final review
- [ ] Developer releases PR
```

**Comment by origami-z** [comment]
16 Oct - docs hidden from site, need examples, review content.

**Comment by origami-z** [comment]
Yes, progress is in lab

**Comment by origami-z** [comment]
push out a week to get component example migrated

**Comment by shey-v** [comment]
6 Nov - in progress.
