### ISSUE TITLE
Progress: Design assets

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2588]
```[tasklist]
### Tasks
- [ ] Characteristics spec in Figma
- [ ] Interactions spec in Figma, where neccessary
- [ ] Component in Figma + component guide
```

**Comment by bhoppers2008** [comment]
[Light branch](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/fdLpkvgZaJv0HJDLeauDWN/Salt-Light-Components?type=design&node-id=9298%3A626&mode=design&t=tosxHf7K1zNB1mkJ-1) for Progress component updates.

**Comment by origami-z** [comment]
23 Oct - in progress
