### ISSUE TITLE
Spinner v2: Design assets

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2590]
```[tasklist]
### Tasks
- [ ] Characteristics spec in Figma
- [ ] Interactions spec in Figma, where necessary
- [ ] Component in Figma + component guide
```

**Comment by bhoppers2008** [comment]
Branch for Spinner updates here: https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/eXw4m45FX4JqUQkJQgNNZ6/Salt-Light-Components?type=design&node-id=6198%3A73968&mode=design&t=nCVLTrxbe1K0ufbY-1

**Comment by origami-z** [comment]
23 Oct - Figma in progress
