### ISSUE TITLE
App Header pattern doc publish and examples

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2666]
```[tasklist]
### Tasks
- [ ] Publish design doc from #2356
- [ ] Example code in storybook
- [ ] Migration guide on Stack Overflow
```

**Comment by origami-z** [comment]
Duplicate of #2669
