### ISSUE TITLE
App Header Pattern publish to site and examples

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2669]
```[tasklist]
### Tasks
- [ ] Publish pattern doc to site from #2356
- [ ] Add examples to storybook
- [ ] Migration QA to StackOverflow
```

**Comment by origami-z** [comment]
17 Nov - Started dev work, design page + examples

**Comment by origami-z** [comment]
22 Nov - PR dev review ready for example matching UITK

**Comment by origami-z** [comment]
24 Nov - PR ready, page design needs discussion with @ivan-calderon
