### ISSUE TITLE
Move Badge to Core

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2702]
```[tasklist]
### Tasks
- [x] Fix existing known bugs, #2633
- [ ] Add all densities and modes to Chromatic snapshot for visual regression (QA stories)
- [ ] Move code, stories, tests, check storybook build and page previews
- [ ] Move site docs, remove 🚧, "in progress", check site preview
- [ ] Fix all linting issue
- [ ] Detailed changeset for both lab and core package, e.g. Switch example in #2626
- [ ] Component UITK migration Q&A on StackOverflow
```

**Comment by origami-z** [comment]
13 Nov - connect with designers to verify examples
