### ISSUE TITLE
Move Progress from Lab to Core

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2731]
```[tasklist]
### Tasks
- [ ] Fix existing known bugs
- [ ] Add all densities and modes to Chromatic snapshot for visual regression (QA stories)
- [ ] Move code, stories, tests, check storybook build and page previews
- [ ] Move site docs, remove 🚧, "in progress", check site preview
- [ ] Ensure No Injection QA Story is there
- [ ] Fix all linting issue
- [ ] Detailed changeset for both lab and core package, e.g. Switch example in #2626
- [ ] Component UITK migration Q&A on StackOverflow
```
