### ISSUE TITLE
Lint CSS to make sure components not using deprecated tokens

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2743]
Also, we should have lint rules to not allowing our own components using [deprecated tokens](https://github.com/jpmorganchase/salt-ds/tree/main/packages/theme/css/deprecated), so that repo-wide characteristics renaming (e.g. #2530) will be safer.

Also, we have [existing stylelint rule](https://github.com/jpmorganchase/salt-ds/blob/main/tooling/stylelint/correct-theme-token-usage/index.js) to use correct characteristics names, we should update it to not allow removed characteristics.

```[tasklist]
### Tasks
- [x] Implement lint rule with warning #3301
- [x] Dradaully remove deprecated tokens in core package
- [x] Make lint rule an error for core package, warning for lab
```

**Comment by mark-tate** [comment]
Related to #1107

**Comment by origami-z** [comment]
> Related to #1107

This isn't a breaking change, deprecated tokens shouldn't be used in our components

**Comment by joshwooding** [comment]
Was closed by #4619
