### ISSUE TITLE
Update Figma file and libraries to reflect Text-to-Content characteristic changes

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2747]
Update Figma file and libraries to reflect Text-to-Content characteristic changes.

Update: 

```[tasklist]
### Tasks
- [x] Theme characteristics Figma file
- [x] Light mode Figma library
- [x] Dark mode Figma library
- [x] Salt 1.0 theme library (variables version)
- [x] Publish Figma library updates internally
```

**Comment by pseys** [comment]
Changes merged to main branch in Figma. Updated libraries ready for release.

**Comment by pseys** [comment]
Hey @bhoppers2008 these changes are ready to publish. Let me know how/when you'd like to do this.

**Comment by pseys** [comment]
Figma libraries published.
