### ISSUE TITLE
Salt 1.0 Figma component library (variables)

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2748]
```[tasklist]
### Tasks
- [x] Create Figma variables driven Salt component library
- [x] Remove dark mode components from Figma variables driven Salt component library
- [x] Move density variables from Figma theme file to component file to aid theme switching
- [ ] Apply space, size, corner radius (large only) variables to all Figma components
```

**Comment by pseys** [comment]
In the process of applying size and spacing tokens to all components. All components have been updated with the exception of Data Grid, Form Fields and Nav item. 

Accordion needs revisiting to ensure text wrapping is consistent with current component. 

All components require QA testing.

**Comment by origami-z** [comment]
22 Nov - Added Salt 1.0 typography styles to Figma theme library and swapped libraries for the Salt 1.0 Figma component library (variables version)

**Comment by origami-z** [comment]
6 Dec - to have meeting with Figma (this afternoon), will impact how we deliver this

**Comment by origami-z** [comment]
11 Dec - met with Figma last week, having a better idea of how to structure Figma libraries (need  a lot of work needed to do).

**Comment by pseys** [comment]
Moving to blocked due to dependency on current Figma limitations and components in Salt 1.0 being a moving target.

**Comment by pseys** [comment]
Following discussion with wider team it was agreed to close this. Although the POC was successful in testing the viability of variables in Figma there is little to no benefit progressing this for Salt 1.0 at this time. All efforts will be put into the release of Salt 2.0.
