### ISSUE TITLE
Salt 1.0 Figma theme library (variables)

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2749]
```[tasklist]
### Tasks
- [x] Create Salt 1.0 Figma theme library with styles linked to variables that matches the structure in code
- [x] Update Foreground characteristic values to Content in order to match changes in code
- [x] Add typography styles for ease of switching – ensures all theme elements are contained within one file and will make duplication/swapping libraries far easier, also reduces the number of files designers have to reference
- [x] Update Salt 1.0 Figma component library to use typography styles contained within theme file
```

**Comment by pseys** [comment]
- Library created and tied into Salt 1.0 Figma component library (variables version). 
- Content characteristic changes published as part of unstable style library.

**Comment by pseys** [comment]
Moving to blocked due to dependency on current Figma limitations and components in Salt 1.0 being a moving target.

**Comment by pseys** [comment]
Following discussion with wider team it was agreed to close this. Although the POC was successful in testing the viability of variables in Figma there is little to no benefit progressing this for Salt 1.0 at this time. All efforts will be put into the release of Salt 2.0.
