### ISSUE TITLE
Salt 2.0 Figma theme library (variables)

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2750]
```[tasklist]
### Tasks
- [x] Create Salt 2.0 Figma theme library
- [ ] Apply simplified palettes
- [x] update typography styles to align to new size ramp
- [ ] Duplicate Salt 1.0 component library (variables), rename to Salt 2.0 component library (variables)
- [ ] Switch style library in Salt 2.0 component library (variables) from Salt 1.0 styles to Salt 2.0 styles
- [ ] Add corner radius to Salt 2.0 Figma theme library as variables options
- [ ] Add corner radius to relevant components in Salt 2.0 component library (variables version)
```

**Comment by pseys** [comment]
Closing issue as approach needs to change based on feedback from Figma. Separating the task out into smaller issues that can be tracked more easily.
