### ISSUE TITLE
Navigation Item

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2872]
```[tasklist]
### Tasks
- [x] Update the logic to make Navigation Item act like a button when a href isn't passed
- [ ] Get feedback
- [ ] Move to core
- [x] Add more explanation on how to use `blurActive` prop in the docs
```

**Comment by joshwooding** [comment]
@alycrys I've updated the issue description to allow the navigation item to act like a Button.

**Comment by alycrys** [comment]
17.01 - PR ready for dev review. Design has reviewed
