### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2879]
```[tasklist]
### Tasks
- [ ] Get Feedback
- [x] Review site doc examples and desciptions
- [x] Implement desktop support
- [ ] Move Drawer to core
- [x] Transition needs standardising to ease in out with perceptible token (plus updating in characteristic spec)
- [x] Update with Salt Scrim
- [x] Update with secondary drawer examples in site
- [x] Review Figma component to align wihn
- [x] Change default open value to false
- [x] Review migration guide
- [x] Optional CloseButton
```

**Comment by bhoppers2008** [comment]
Changes from UITK Drawer

- Ensure that site docs/migration guide give recommendation to use Border Layout, rather than Drawer, when teams require equivalent of UITK Inlaid Drawer. Salt Drawer will only overlay. 
- Salt's Drawer is always modal (needs capturing in docs). A docked behaviour would be created by AD teams by using a panel and styles to expand and collapse a non-modal surface.
- Custom Close Button label example not required.

**Comment by bhoppers2008** [comment]
**Figma**
Salt Drawer spec is [here](https://www.figma.com/file/eAySdIQO4e6icsXk5ZOaoL/Drawer?type=design&node-id=1521%3A426&mode=design&t=G9Ld2XxlVOL8Agwm-1).
Salt Drawer component is released.

**Comment by bhoppers2008** [comment]
Things to discuss from KO

- Should the Drawer fill the entire application or just a container/region - Yes. In order to satisfy the Data Grid requirement of having a drawer within the area of the grid.

**Comment by feliciackh** [comment]
30/1 Takeaway post catch up with @bhoppers2008
- remove min height/min width for all positions
- default primary & default secondary example to have no content 
- add one more example showcasing optional close button (total to 6 examples altogether)
- improve example for bottom drawer: use Salt Cards and layouts
- improve examples for left and right drawer: @bhoppers2008  to share mock ups by mid morning Wednesday
- update docs to include recommendation for users to set drawer width

**Comment by mark-tate** [comment]
https://www.saltdesignsystem.com/salt/components/drawer/examples
