### ISSUE TITLE
Segmented Button Group

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2883]
## Description
A Segmented Button Group is a control that shows a list of actionable buttons, flush with separators between them.

```[tasklist]
### Tasks
- [x] Research other implementations
- [x] Figure out the height of the separators e.g. selectable, base - spacing-100 (switch)
- [x] Figure out focus management e.g. Roving tab-index (arrow keys) / Standard focus (tab)
- [x] Figure out focus ring contrast
- [ ] Write guidance on usage e.g. how does it differ from Toggle Button Group/Toolbar
```

Notes:
- Different from Toggle Button Group as its prime use-case is with "normal" buttons which do not have a pressed state and won't support exclusive selection.
- Will form the Split Button pattern when used with the Menu Button pattern

**Comment by yunjungyeh** [comment]
8 Feb Kick Off with @joshwooding @bhoppers2008 @mikearildbrown 

Requirement:
All variants / all density 
Use Buttons and add separator, 

Keyboard
Accessibility 
Focus ring

Switch height or checkbox height


Part of Split Button pattern

**Comment by yunjungyeh** [comment]
Discussed with @joshwooding  focus management should be Standard focus (tab)

**Comment by yunjungyeh** [comment]
15 Feb - Characteristics/ Accessibility/ Interactions Specs are done and reviewed with @joshwooding @bhoppers2008

**Comment by yunjungyeh** [comment]
5 Mar - Decision made: using Primary Separator. Spec updated
5-6 Mar - Component sets added to Light and Dark

**Comment by yunjungyeh** [comment]
6-7 Mar - Component Guide, reviewed with @bhoppers2008 and merged

**Comment by joshwooding** [comment]
Available in core https://www.saltdesignsystem.com/salt/components/segmented-button-group/examples
