### ISSUE TITLE
Update Salt DS comms for UITK

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2996]
This is issue will consolidate our internal comms about Salt for UITK consumers to easily access. It includes the following tasks:

```[tasklist]
### Tasks
- [ ] Move UITK's [Salt FAQ](https://uitk.gaiacloud.jpmchase.net/salt/frequently-asked-questions) page to an 'FAQ' tab in the [new internal site](https://developer.dev.aws.jpmchase.net/salt/index).
- [ ] Update copy in new FAQs page with [up to date content](https://sites.jpmchase.com/:w:/s/JPMUIToolkit/EUSMktEqwYRAnc-WeamXIg8B-QkcSeumJYlS61q-QqvNUA?e=LlZVrd) from @mikearildbrown.
- [ ] Publish the new [Salt 101 content](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/_layouts/15/Doc.aspx?sourcedoc=%7B438BB227-DDCA-4794-84E2-A090AF40FB9A%7D&file=Salt%20One%20Pager%20Feb%202024.docx&action=default&mobileredirect=true) to a new tab in the internal site. @mikearildbrown to propose appropriate tab name.
- [ ] Ensure 'Gradual migration link' in 101 page is updated to point to the new internal FAQ page.
- [ ] Merge the [Salt<>UITK comparison table](https://sites.jpmchase.com/:x:/s/JPMUIToolkit/ESIQC_KxxvBMlus0uPV27MgBvaEyKjG9V1TqSJzB6vJXww?e=kkLJSd) into the new FAQs page. Use existing mosaic table styling.
- [ ] @mikearildbrown to determine what happens to existing [Overview](https://uitk.gaiacloud.jpmchase.net/salt/) content (from UITK's Salt tab). What do we move to the internal site? What do we merge and where? What do we remove?
- [ ] Add new set of [Salt link (cards)](https://www.figma.com/file/E9m3rGspmw7Mv4La5TCAmV?node-id=0:2950&mode=design#696084259) to the UITK home page (beneath the row with Components and Patterns cards). 
- [ ] @mikearildbrown to review copy for proposed link cards (in Figma file) + approve image for Getting started link card.
- [ ] Link 1: Goes to go/salt-ds/
- [ ] Link 2: Goes to go/whysalt/
- [ ] Link 3: Goes to internal site's '101' page.
```

###Notes

- For this release go/whysalt/ content will remain in its current blog location.
- Comparison table will adopt existing mosaic table component styles.
- @mikearildbrown to consider what to do with existing UITK site Salt-related blog links (currently on overview page).

**Comment by tomhazledine** [comment]
There's a PR on the internal site's repo: [`salt-ds-internal-docs` PR #6](https://bitbucketdc.jpmchase.net/projects/JPMUITK/repos/salt-ds-internal-docs/pull-requests/6/overview)

It adds the FAQ page (including adding it to the site's header menu) with the comparison table and amended copy (as per [this doc](https://sites.jpmchase.com/:w:/s/JPMUIToolkit/EUSMktEqwYRAnc-WeamXIg8B-QkcSeumJYlS61q-QqvNUA?e=LlZVrd))

## Notes

* The comparison table has been broken up into separate tables for each sub-heading (Markdown's table support is limited, so this looked like the best option).
* I've added the [UITK Salt page](https://uitk.gaiacloud.jpmchase.net/salt/) content to the new internal site's homepage. I'm imagining that this will be quickly replaced by the "101" content. Until that 101 content is in place, the "Getting started" card on the old UITK site will point to the internal homepage.
