### ISSUE TITLE
Theme Next: Brand Theme

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3287]
Implement additional options 

```[tasklist]
### Tasks
- [x] Mechanism to release this early without breaking change (`UNSTABLE_SaltProviderNext`)
- [x] Rounded corner option (#2989)
- [x] New color palette (#3255)
- [ ] https://github.com/jpmorganchase/salt-ds/issues/3368
- [ ] https://github.com/jpmorganchase/salt-ds/issues/3394
```

**Comment by origami-z** [comment]
Released in #3507
