### ISSUE TITLE
Scrim

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#331]
Scrim should be updated to be a simple component displaying a semi-transparent overlay above content. 

```[tasklist]
### Tasks
- [ ] Remove focus trap behaviour
- [ ] Scrim should allow children to be passed in e.g. Spinner
- [ ] Scrim can be shown by clicking a button and hidden by clicking it, this could be achieved with an onClick event
- [ ] Scrim should be a div
```

**Comment by ZarkoPernar** [comment]
## Preparation

-   [ ] Existing defect backlog reviewed/evaluated, prioritized, and selected
-   [ ] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
-   [ ] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
-   [x] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
-   [x] Usability testing plan defined or deemed unnecessary
-   [x] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads

## Development

-   [x] Component implemented in/ported to TypeScript
-   [x] 3rd-party dependencies removed
-   [x] JSS converted to CSS
-   [ ] CSS upgraded to use characteristics
-   [x] Selected defects resolved
-   [x] Component API finalized
-   [x] Necessary refactoring completed
-   [x] Selected enhancements added

## Testing

-   [x] Functional test script is implemented in Cypress and passes
-   [x] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
-   [x] QA (v1-2 visual regression) test passes
-   [x] Automated Axe tests added and pass

## Examples

-   [x] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
-   [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)

## Deployment

-   [ ] Codemods for migration created and verified
-   [ ] Reviews/Signoff
-   [ ] Dev production review
-   [ ] Design review
-   [ ] Product signoff
-   [ ] ADA review
-   [ ] Documentation
-   [ ] Dev docs content provided
-   [ ] TK1→Odyssey migration guide provided
-   [ ] Design docs provided
-   [ ] Consolidated documentation produced by combining dev content, migration guide, and design docs
-   [ ] Consolidated documentation published on Storybook
-   [ ] Consolidated documentation reviewed and updated according to user feedback
-   [ ] Figma symbols
-   [ ] New Odyssey Figma symbol created
-   [ ] Figma symbol references updated to use new Figma symbol

**Comment by ZarkoPernar** [comment]
@joshwooding do we want to revisit Scrim based on the discussions from last week? Is it enough of a priority?

**Comment by ZarkoPernar** [comment]
Since this work would involve Dialog we could delay it until Dialog is next on the todo

To recap:
- don't treat Scrim as a fully functioning and semantic dialog, refactor to offload this functionality on to Dialog
- change the default behavior to close with escape to be true

**Comment by joshwooding** [comment]
09/01 - Making progress, will set up meeting to discuss progress @bhoppers2008 to send design links

**Comment by lilyvc** [comment]
17/01 - PR ready for review
