### ISSUE TITLE
Pagination pattern with total item and per page count 

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3313]
Pepper pagination pattern emphasis on item count rather than page count, including a dropdown selecting item count per page.

```[tasklist]
### Tasks
- [ ] Pepper team design 
- [ ] Build an example in Salt storybook
- [ ] (TBD) publish as Salt pattern with Salt information
```

**Comment by origami-z** [comment]
Remove priority, will be built as a pepper pattern
