### ISSUE TITLE
Divider component design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3320]
Design spec for divider component.

Notes:
- Work on both Salt 1 and 2
- Characteristic - to follow Salt next button (in Salt 1 it's called separable https://github.com/jpmorganchase/salt-ds/blob/main/packages/theme/css/characteristics/separable.css)
- Orientation support (Horizontal / Vertical)
- another issue for replacing separator (e.g. segmented button group, )
- From Dev POV, it's easier to work on Salt 1 first
- For Pepper they will create the thickness (which won't be part of Salt)

```[tasklist]
### Tasks
- [x] Characteristic Spec Salt 1
- [x] Characteristic Spec Salt 2
- [x] Decision about the name (Divider vs Separator): Divider
- [x] Site examples / Content
- [ ] separable-primary-borderColor update in Code / Figma
- [ ] Figma Component sets
```

**Comment by mark-tate** [comment]
Spec - design defined but missing documentation + figma support
