### ISSUE TITLE
Theme Next - Heading typography option Amplitude

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3368]
```[tasklist]
### Tasks
- [x] Add new foundation typography headings token, default to Open Sans #3396
- [ ] Point h1/2/3/4, display 1/2/3 to new heading token
- [x] Add new palette layer types (heading / body), point text characteristics to palette instead of foundation ##3391
- [x] Add new amplitude typography foundation variable #3396
- [ ] Add new amplitude font-face declaration file
- [ ] Upload Amplitude font for storybook to use (but not distribute through npm package for licensing issue)
- [x] Add additional theme-next in palette point heading to amplitude #3396
- [x] Add additional option to Unstable SaltProvider, to switch between 2 font options #3396
- [x] Add new toggle to storybook toolbar to demo #3396
- [x] Font weight remapping #3500
- [x] Update theme next doc with relevant information
```

**Comment by origami-z** [comment]
Released in #3507
