### ISSUE TITLE
Multi-select list item sync in Code and Design

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3546]
### Area

UI Components, Documentation

### The problem

About adding secondary labels for components, we can achieve Checkbox as what we’ve had in code.
However, multi-select list item is using Checkbox in build and Figma, the alignment would be different (as screenshot shown below), so need to discuss how to sync (e.g. in Figma consumers can manually adjust it for the List item?)
Another difference is in code there can be an Avatar between the box and the Value container, for now this can't be achieved in design as the same in code.

### The solution

```[tasklist]
### Tasks
- [x] Update the storybook example (#3556)
- [ ] Create a complex Sticker - put a swap between checkbox & text, the custom checkbox + Avatar or guidance for Figma overwrite cc @bhoppers2008 
```

### Alternatives and examples

@joshwooding has been updating the example in other issue.

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by yunjungyeh** [comment]
closes #3556

**Comment by mark-tate** [comment]
Garlic: Design updates published and code and design are back in sync

**Comment by yunjungyeh** [comment]
Discussed and reviewed with @joshwooding, updated and merged
