### ISSUE TITLE
Update Button component to use new styles

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#3630]
New variables have been added to the Salt (next) styles library to accommodate Bordered Button. 

- The `button` component needs to be updated to use the new variables.
- `appearance` and `color` props needs to be added to Button
- `appearance: solid | outline | transparent` `color: neutral | accent` need to be added to Button

Figma implementation of #3325 
```[tasklist]
### Tasks
- [x] Update Salt Theme Characteristics file in Figma
- [x] Update Light mode library
- [x] Update Dark mode library
- [x] Update Light components library
- [x] Update Dark components library
- [x] Update Salt (Next) Styles library
- [x] Update Salt (Next) Components and Patterns Library
- [ ] https://github.com/jpmorganchase/salt-ds/issues/3889
- [ ] https://github.com/jpmorganchase/salt-ds/issues/3890
```

**Comment by pseys** [comment]
For the updated Button component I think the least disruptive solution is to do the following: 
 
- Change `cta button` to `accent button`
-- Add `appearance` as a prop with 3 options `solid` (as default), `outline` and `transparent`
- Change `primary button` to `neutral button`
-- Add `appearance` as a prop with 3 options `solid` (as default), `outline` and `transparent`

### TBC 
- Change all instances of `secondary button` across the component library to use `neutral button` set to `transparent`
- Remove `secondary button`

**Comment by mark-tate** [comment]
Goal: S(3)
Figma published, tokens ready by 25/06/24
Dev work to start 26/06/24

**Comment by pseys** [comment]
The `button` component is complete and ready to publish, however, I need to check through all of the components it is dependent on and change any references to `cta|primary|secondary`

**Comment by pseys** [comment]
All Figma components have been updated. `button` is ready to publish in Figma.

**Comment by joshwooding** [comment]
Blocked by #3325

**Comment by pseys** [comment]
The theme spec for #3325 is complete and has been handed over to development. I'm now able to start mapping the new tokens to the legacy and next style libraries so the Button components can be updated.

**Comment by pseys** [comment]
In the process of updating the Characteristics Theme file. Palette tokens have been updated.

**Comment by pseys** [comment]
Theme Characteristics file updated.

**Comment by pseys** [comment]
Salt (Next) Style Library updated in branch. Branch has been merged. Update has been published.

**Comment by mark-tate** [comment]
Goal: more examples added to Storybook

**Comment by pseys** [comment]
Light and dark mode library changes in progress. Branches match the title of this issue.

**Comment by mark-tate** [comment]
@navkaur76 are you able to review this for @pseys ?
