### ISSUE TITLE
Salt Figma Guides Plan

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3652]
Create the plan with detailed scope and timeline for updating Salt Figma Guide Library that include Salt Next
**the set goal: By the end of Q3 all the guides will be updated**

**How long do we want to take to update them?**
Depends on the priority, ideally in 3-4 sprints especially after more people using Salt Next

**How many are there?**
so far 41 (40 components/ 1 pattern)  will add components: Toolbar, Tree, Comments → 44

**How long will they take?**
Approximately 140h / 20-24 working days

**When will they be done by?**
Goal: By the end of Q3 all the guides will be updated.
Yun will start to do some (3 guides) first in the next sprint, and other designers can start to pick up in the following sprints.

```[tasklist]
### Tasks
- [x] Create a confluence page with detailed scope and timeline
- [x] Discuss with Ben and set the goal
- [x] Add the individual tasks to GitHub
```

**Comment by yunjungyeh** [comment]
Thu 4 July - created issues for all the individual tasks
