### ISSUE TITLE
Migrate Figma backlog (in confluence) to GitHub backlog

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3663]
Migrate Figma backlog (in confluence) to GitHub backlog by EOS
Size: S
```[tasklist]
### Tasks
- [x] List in Salt Figma Cleaning and Tidying
- [x] Icon search
- [x] Figma Salt Next metadata
- [x] Bug found in Icon Salt 1 (not resizing properly after update icon type)
- [x] To-dos in Release Review List for Salt 1
- [x] To-dos Release Review List for Salt Next
```

**Comment by yunjungyeh** [comment]
Mon 8 July - all the tasks from figma comments and in confluence (listed above in the tasklist) are added to GitHub issues 
cc @bhoppers2008 @origami-z @joshwooding @mark-tate
