### ISSUE TITLE
Testing component tutorial format for Salt Figma Knowledge Share

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3664]
Testing component tutorial format for Salt Figma Knowledge Share
EOS goal: 
Have the materials for testing component tutorials format and share with the LOB designers

```[tasklist]
### Tasks
- [x] Record tutorial (Avatar) - first version
- [x] Get Feedback from Ben/Zhihao
- [ ] (WIP) Avatar Playground
- [ ] (WIP) Record new versions of the videos
- [ ] Have the materials for testing component tutorials format
- [ ] share/test with the LOB designers
- [ ] discuss/work on Internal site Knowledge share/Design page with Honey & Mark
- [ ] have a knowledge share format to follow before Q3
```

**Comment by mark-tate** [comment]
returned to backlog until prioritized @bhoppers2008
