### ISSUE TITLE
Figma Bugs Fix: Icon, Status Indicator (sizes not correct after variable applied in Icon Library)

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3672]
After Icon library applied variable, there are Figma Bugs that need to be fixed
Components that use Icon, Status Indicator, Button etc.

```[tasklist]
### Tasks
- [x] Fix: Icon sizes
- [x] Fix: Status Indicator and Icon bugs in Button/Avatar
- [x] Fix: Patterns that use Button, Icon bugs in Toggle Button
- [x] Fix: Banner - Button icon size update (reset to remove variable)
- [x] Fix: Form control component: Dropdown/Combobox/Single Date/Stepper Input
- [x] Fix: Calendar - button icon reset (to remove variable)
- [x] Fix: Link - icon reset (to remove variable) and update size
- [x] Fix: Pagination - button icon reset (to remove variable)
- [ ] Fix: Pill - icon reset (to remove variable) and update size
- [ ] Fix: Toast - button icon reset (to remove variable)
```

**Comment by yunjungyeh** [comment]
**Figma Bugs fixed on Fri 28 June with the release:**
- Fix: Icon sizes
- Fix: Status Indicator and Icon bugs in Button/Avatar
- Fix: Patterns that use Button, Icon bugs in Toggle Button


**Figma Bugs fixed and published on Mon 1 July:**
- Fix: Form control component: Dropdown/Combobox/Single Date/Stepper Input
- Fix: Calendar - button icon reset (to remove variable)
- Fix: Link - icon reset (to remove variable) and update size
- Fix: Pagination - button icon reset (to remove variable)
- Fix: Pill - icon reset (to remove variable) and update size
- Fix: Toast - button icon reset (to remove variable)
