### ISSUE TITLE
Salt (Next) release announcement

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3677]
```[tasklist]
### Tasks
- [x] Create 1 word doc where we can consolidate
- [x] 5 sections (below) in that word doc
- [x] Move source content into one word doc
- [x] Refine content [allocate/ together]
- [x] Agree where content lives (internal/ external) [Together]
- [x] Update Internal Site
- [ ] Publish Figma Library [BH or YY?]
- [x] Publish pages [ZC]
- [x] What is the publish/release process in the future? Should Salt 1 & Salt Next be released together (in the same email?)
- [x] Release Banner [YY]
- [x] Announcement News in Internal Site [YY]
- [x] Announcement Communication (Email/Symphony/Teams)[YY]
```

```[tasklist]
### Announcement Communication
- [x] An Email Newsletter (similar to "Pepper Pattern Library Goes Live!" in the internal site)
- [x] Channels (Symphony/teams)
- [x] News report (Like "Pepper Pattern Library Goes Live!" in the internal site)
```

**Comment by yunjungyeh** [comment]
[ZC] ‘Theming’- People interpret it as ‘make it look different’. What’s the better way to describe it? ‘Styling options of Salt theme’
[BH] ‘Endorsed JPM Brand foundations enable delivery teams to create optimised design languages using brand approved styling options for application users/ use cases.’
 
1.       Create 1 word doc where we can consolidate
2.       5 sections (below) in that word doc
3.       Move source content into one word doc
4.       Refine content [allocate/ together]
5.       Agree where content lives (internal/ external) [Together]
6.       Publish [ZC]
7.       Release note/ email [YY]

**Comment by yunjungyeh** [comment]
Thu 4 Jul - document reviewing WIP, discussed release banner and WIP

**Comment by yunjungyeh** [comment]
Added a task: to discuss - What is the release process in the future? Should Salt 1 & Salt Next be released together (in the same email etc.?) cc @bhoppers2008 @origami-z @pseys

**Comment by yunjungyeh** [comment]
12 Fri - Salt Next announcement communications:
- A Newsletter (similar to "Pepper Pattern Library Goes Live!" in the internal site)
- Channels (Symphony/teams)
- News report Home page - (like "Pepper Pattern Library Goes Live!" in the internal site)

For the updates releases in the future, will be with the same release email that Salt 1 originally has

**Comment by yunjungyeh** [comment]
15 July - News page PR created for internal site - awaiting for links and review then can be published

**Comment by origami-z** [comment]
Jul 15 - #3814 ready to be merged

**Comment by yunjungyeh** [comment]
News page in the Internal site updated. Announcement Communication (Email/Symphony/Teams) done! @origami-z @bhoppers2008
