### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#369]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [ ] Overlaid drawer
- [ ] Edge positioning
- [ ] Hide/show scrim
- [ ] Hide/show close button
- [ ] Sliding animations
- [ ] Example, Docked drawer with content (navigation?), Expand button trigger, Collapsed view
- [ ] Example: Overlay docked drawer with content (form fields?), Secondary fill, External trigger, Total collapse
```

This component will replace Drawer

**Comment by maj-stella** [comment]
Recommendation for aria attributes in the Layer Layout Left Simple Usage example when Scrim component is not used:

When dialog opens, the focus is placed in the first form field.

Change `<h1>` to `<h2>` to be consistent with Default Layer layout structure.

```
<div class=“uitkLayerLayout” role=“dialog” aria-modal=“true” aria-labelledby=“dialog_title” aria-describedby=“dialog_desc”>

<div class=“uitkFlexLayout”>
<h2 id=“dialog_title”>Section title</h2>
<p id=“dialog_desc”>
	Incididunt adipisicing deserunt nostrud ullamco consequat consectetur magna id do irure labore fugiat. Eiusmod pariatur officia elit ad. Ullamco adipisicing Lorem amet velit in do reprehenderit nostrud eu aute voluptate quis quis.
</p>
</div>
```

**Comment by maj-stella** [comment]
Layer Layout Bottom Simple Usage example:

Change `<h1>` to `<h2>` to be consistent with Default Layer layout structure. Also `<h2>` headings ‘Laborum in sit office connect’ to `<h3>`.

`<div class=“uitkLayerLayout” role=“dialog” aria-modal=“true” aria-labelledby=“dialog_title”>`

`<h2 id=“dialog_title”>Section title</h2>`

There is a lot of content do be read out with aria-described by as a single unbroken string; therefore place focus at `<h2>Section Title</h2>` with `tabindex=“-1”`. This makes it easier to read the content for screen reader users.

Move ‘Open Layer’ button closer to the content (to the left). People with magnification software would struggle to see it or they would not be aware that there is a button to the right.

**Comment by JoanaMMoreira** [comment]
@maj-stella here's the PR link for these changes: https://layer-ada-tweaks.uitk.pages.dev/?path=/story/core-layout-layerlayout--default-layer-layout

I didn't move the "open layer" button to the left as I believe it is a bit counter intuitive from a UX perspective but it would be good to check with the designers

**Comment by origami-z** [comment]
Adding some issues found after debugging with @lilyvc

- It's not possible to disable `fullScreenAtBreakpoint`, i.e. not going full screen at all scenarios. Maybe setting the prop to `null` could be a possibility
- The doc doesn't mention the [Left example](https://uitk.pages.dev/?path=/story/core-layout-layerlayout--layer-layout-left) width applied is in [a custom CSS](https://github.com/jpmorganchase/uitk/blob/caababeb1f82e9100e57e21028d1316d1b1b1103/packages/core/stories/layout/styles.css#L241) in storybook, not part of the component. It took a while to figure out why pure component won't appear the same locally. Also, maybe it's good to include a default `width` (e.g. `x * unit size`) and let the user to override.
- The name of [`useIsViewportLargerThanBreakpoint`](https://github.com/jpmorganchase/uitk/blob/caababeb1f82e9100e57e21028d1316d1b1b1103/packages/core/src/utils/useIsViewportLargerThanBreakpoint.ts#L7) is a little confusing. In [`LayerLayout`](https://github.com/jpmorganchase/uitk/blob/2cb9429f70fe1bf395ba6f5a5cd58a557f8c9c4f/packages/core/src/layout/LayerLayout/LayerLayout.tsx#L89), it's used as "viewport smaller than breakpoint"..?

cc @mark-tate

**Comment by parsakhan21** [comment]
July 14 - use existing examples - writing tests; PR ready for review

**Comment by JoanaMMoreira** [comment]
20/07 update - we're going to replace Scrim with a version built using Floating UI's focus manager and remove some of the props (disableAnimations, disableScrim and scrimProps)

**Comment by JoanaMMoreira** [comment]
July 28 - Issue with Drawer docs has been fixed. Design assets are pending but the component is in Core ready for release

**Comment by AnniaT** [comment]
@dplsek reviewed and some feedback to be addressed.

@navkaur76 to finalise spec once back

**Comment by james-nash** [comment]
PR for docs conversion from Word to MDX is here: https://github.com/jpmorganchase/salt-ds/pull/2111

**Comment by joshwooding** [comment]
Created tickets to track left over: #2130 #2129
