### ISSUE TITLE
Form Field - Icon spacing in general: where do we use 50, 75, and 100

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3764]
```[tasklist]
### Tasks
- [ ] Discussion
- [ ] Solution
- [ ] Update Salt 1 Light/Dark
- [ ] Update Salt Next
- [ ] Update in code
```

**Comment by bhoppers2008** [comment]
@amritadesmet spacing between icons and text (the title is misleading)... may be a nice one to accompany with icon size alongside text.

**Comment by mark-tate** [comment]
Can be delivered through token documentation

**Comment by mark-tate** [comment]
@amritadesmet still a Q3 goal or can this be delivered through some other ticket ?

**Comment by kriskoder** [comment]
@honey-chang icon before headings and display in our site docs are in `Card` in `Toggle group` and `Disabled toggle group`

**Comment by honey-chang** [comment]
Currently below components have icon paired with headings style.
- Selectable Card
- Dialog
- Vertical Navigation
- Header Block(Pattern)

**Comment by joshwooding** [comment]
Moved into the next sprint

**Comment by bhoppers2008** [comment]
Migrate to CIBDESIGNSYSTEM Jira board.
