### ISSUE TITLE
Data Grid v1

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#381]
Figma Spec: https://figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid
- ADA Spec: https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=608%3A11050

___

- [x] https://github.com/jpmorganchase/uitk/pull/674

___

## Densities
- [x] Grid should support high, medium, low and touch densities
- [x] Density should be changeable in dev-time and runtime
## Themes
- [x] Grid should work in light and dark modes
## Background variants
- [x] Three variants should be supported: primary, secondary and zebra
## Cells
- [x] User should be able to specify cell value getters per column
- [x] Text alignment should be configurable
- [x] User should be able to specify react components for cell values (per column)
## Columns
- [x] Columns should be resizable
- [x] Column dividers should be optional and configurable by a property of the Grid component (on/off)
- [x] Text layout of column headers should be configurable
- [x] Header content should be configurable per column (by providing react components)
- [x] Column groups should be supported
- [x] User should be able to pin columns/column groups left or right
- [x] When client space is wider than all columns combined, the empty space should be filled with a fake empty column
## Virtualisation
- [x] Grid should render only rows and columns visible for the user. Scrolled-out parts of the grid should not be rendered.
## Selection
- [x] Grid should support single and multi-row selection modes
- [x] Grid should provide columns for selecting rows (checkbox column for multi-row selection and radio button column for single row selection mode). These columns should be optional.
- [x] Rows should be selectable by clicking on them (shift, ctrl, meta buttons should be supported)
## Keyboard navigation
- [x] Arrow keys, page up/down, tab, ctrl, home, end should be supported
## Scrolling
- [x] User should be able to scroll the grid horizontally and vertically using scrollbars and mouse wheel

**Comment by bhoppers2008** [comment]
Features added to V1 in addition to above, include:

- Editable cells
- Cell range selection (ctrl + shift selection)

All features + documentation still need reviews:

- ADA
- Content
- @dplsek does this need further design review?

FYI @parsakhan21

**Comment by parsakhan21** [comment]
10/24: need to review css part. Mtg with Darrin later today. Further design review will be conducted with Darrin (identify the characteristics missing - figure out strategy). 
ADA - iterative process. Its a big piece of work so may consider outsourcing ADA part?  
Technical documentation/storybook examples/ ADA keyboard spec/ADA spec all ready for a first pass review.

**Comment by parsakhan21** [comment]
10/25 -  Sion completed the content review of Data Grid and submitted a PR

**Comment by parsakhan21** [comment]
10/26 
We need to start documenting the grid to align with our new spec formats, i.e., like any other Odyssey component.
In this case, specifically we need an ADA spec which documents the interactions for V1.
Per last update, we’ll resolve the interactions observed and produce an ADA spec documenting these interactions clearly.
Design will wrap up the ADA spec by the end of next week, **Fri Nov 4th and handover to Stella.**
**Stella** will then take responsibility for **adding ARIA requirements and signing off on that spec.**
**The review will be conducted against the same two stories below. I.e.,:**
[Multi select grid](https://uitk.pages.dev/?path=/docs/grid-new-grid--grid-example)
Communicating and making multiple selections using checkboxes
Using editable cells
Understanding read-only cells
Identifying column headers
Identifying group column headers
(Other mechanisms for making selection–tbc [@Plsek, Darrin (CIB, USA)](mailto:darrin.plsek@jpmorgan.com))
[Single select grid](https://uitk.pages.dev/?path=/docs/grid-new-grid--single-row-select)
Communicating and making single selections

**Comment by bhoppers2008** [comment]
@maj-stella @parsakhan21 

Accessibility spec is ready for review-link in issue above.

Following discussion on our side, the scope for v1 is reduced to the interactions documented in this spec. Interactions covers:
1.	Cell navigation
2.	Row selection
3.	Editable cell interaction

Some things to note:
•	The ARIA spec is only a draft by me, it will need updating based on your input. 
•	The visual design spec documents the requirements that we clarified with the firm’s DAKB team (specifically Kati Allen, Ken Pettri and Adrian Roselli).
•	Keyboard interactions are mostly informed by w3, with some additional interaction details informed by contributors.
The link is also added to the [issue](https://github.com/jpmorganchase/uitk/issues/381) and I’ve added you as an assignee.

**Comment by ZarkoPernar** [comment]
Great work on this @bhoppers2008! 👏

**Comment by james-nash** [comment]
11/24: Work to fix failing tests in ongoing. A11y issues being discussed (meeting today).

**Comment by bhoppers2008** [comment]
@ararus @ZarkoPernar @joshwooding design review complete. Can be found [here](https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=2406%3A110908&t=qJD4jhdoEu0jGnUt-1).
