### ISSUE TITLE
Add size variables to Country Symbol library

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#3851]
Following the removal of Country Symbol as a component in Salt Next library, size variables need to be applied to the Country Symbol library, so users can correctly scale symbols.
```[tasklist]
### Tasks
- [x] Update width and height for each symbol component to use only variables
- [x] Test country symbols to ensure density variables work
- [x] Merge Figma branch to main
- [ ] Publish updated Figma library
```

**Comment by mark-tate** [comment]
CSS variables moving to the country symbol package.
Further discussions on-going.

**Comment by pseys** [comment]
I've updated the Country Symbol Figma library to use variables size-base and size-flagWidth (the latter only for sharp). This is currently in a branch ready to merge and publish. 

@bhoppers2008 need to ensure you're happy with this. The symbols were 72px high, but will now be HD base, so 20px in height by default. We also need to ensure this doesn't break Salt legacy components or impact Salt next components. 

FYI @yunjungyeh

**Comment by mark-tate** [comment]
Will be published in next release
