### ISSUE TITLE
Update Contact Details pattern examples with link styling

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#3853]
Visual underline to indicate link styling is currently missing from the Contact Details stickersheet. The email address within the examples should be displayed with an underline. 

**Design effort:** 

- Figma stickersheet: update the default examples to display the example email address as a link. Note: not the list or list group examples.
- Pattern page: update examples and any relevant annotations 

**Dev effort:**

- Storybook examples update (functional + visual change)
- Site pattern page update
```[tasklist]
### Tasks
- [x] (Design) Figma stickers: Light/Dark, Next
- [x] (Design) Update site examples
- [ ] (Dev) Storybook examples update (functional + visual change)
- [ ] (Dev) Site pattern page update
```

**Comment by yunjungyeh** [comment]
26 Sep - Had a catch up with @navkaur76 

To check with @origami-z 
- if the examples in pattern page should be updated? depending on - if email will alway be a link or they can choose?
- Should email using Link style in Figma?

Goals:
- Update Figma stickers
- Update Site examples
- Zhihao update storybook examples / site

**Comment by origami-z** [comment]
We should pick one design direction, one close example would be Outlook contact cards, which shows them as email link.

Given this is a pattern, a user would be able to choose whether they want to implement it as Link or pure text.

**Comment by yunjungyeh** [comment]
Checked with Zhihao, updated Figma stickers:
The email text parts now follow what Link components in the libraries do, which are different in Light/Dark and Next.

- Salt Light/Dark: the email is using text style - Link
- Salt Next: using command + U to make Body Default underlined

cc @origami-z @navkaur76 @bhoppers2008

**Comment by yunjungyeh** [comment]
PR #4197
