### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by ImmanuelBaskaran** [jpmorganchase/salt-ds#392]
Status: Not recommended to use

```[tasklist]
### Tasks
- [x] Remove render prop API
- [x] Remove built-in link
- [x] Maybe remove built-in close button
- [x] Re-evaluate emphasize
- [ ] Banner ADA review
- [x] Banner Content review
- [x] Banner move to core
- [ ] Banner interactions spec (UX)
- [ ] Banner accessibility spec (UX)
- [ ] Banner characteristics spec (UX)
- [ ] Banner component guide (UX)
- [ ] Banner Figma components (UX)
```

**Comment by alycrys** [comment]
24.04 - KO meeting with Darrin set for 25.04

**Comment by bhoppers2008** [comment]
@dplsek Some answers below:

1. As it stands the token you're referring to is size-adornment-gap @6px. It was defined as part of the form field work which doesn't have icon scaling. We can evolve that token (or the size tokens) as needed.
2. That's the current plan.
3. If there's a business case for a custom icon then sure, i'd agree with that, but i don't think we should allow the icon to be turned off and not replaced by anything. It's a messaging component and we need to rely on more than colour to communicate the messaging/state.
4. Yes please :) Its been on the backlog forever!

Might be worth checking the banner in the UITK site form pattern. I think the only addition is the expandability. I wouldn't make this a v1 feature, unless you think there's a business case to include it. Might also be worth looking at the updated forms pattern work that shey did. She included some guidance on banner usage that may or may not be applicable.

**Comment by dplsek** [comment]
@alycrys I've created the characteristics spec for the banner and added it here:

https://www.figma.com/file/8oJlx8xG3HQNjMyTwwzQvX/Salt-Banner?type=design&node-id=1626%3A280234&t=xRHbs5YC8963xrAT-1

It is spec'd using the proposed spacing ramp that we would like to test first on this component. @joshwooding @libertymayc Can you confirm if we have created this ramp in code yet?

Also, can someone @pseys @bhoppers2008 @joshwooding @libertymayc remind me how we intend on creating the size-stack token, which is equivalent to size-base + spacing-50 top and bottom:

https://www.figma.com/file/WuHHeAVuvphplbrNmrZy6I/Size_Spacing_Experiment?type=design&node-id=78%3A58255&t=ItRoT5T4nDyf1veY-1

**Comment by bhoppers2008** [comment]
Design review complete.

- Some small documentation updates.
- Finalised multiline approach with @dplsek

**Comment by dplsek** [comment]
@bhoppers2008 just want to confirm, do you now consider both the interaction spec and ADA spec complete? I want to just tick the boxes above in the task list if so. Let me know. Thanks.

**Comment by parsakhan21** [comment]
@bhoppers2008  following up on Darrin's question above. thanks! cc: @dplsek

**Comment by dplsek** [comment]
Completed light and dark components; tested via component playground; created component guide page.
