### ISSUE TITLE
Progress v1

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/salt-ds#394]
```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [x] Linear and circular variant
- [x] Determinate value
```

**Comment by parsakhan21** [comment]
July 17 - dev: pr ready for review; designs - to be assigned

**Comment by joshwooding** [comment]
21/07 - Pr been approved, waiting for merge. Design - tokens need some work but no major changes. should talk about responsiveness

**Comment by parsakhan21** [comment]
July 24 - dev: in labs; docs in progress ; design - in progress (working with paul) - design docs/specs can be ready for tomorrow

**Comment by bhoppers2008** [comment]
@ivan-calderon @parsakhan21 design review complete... left a suggestion for the linear Figma component build.

**Comment by AnniaT** [comment]
Dev complete - design will be done by COP - release day to labs tbc.

**Comment by ivan-calderon** [comment]
Design complete and Figma branches ready to be merged:

- Progress [Light](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/euPigciwzoNoBvZ5RKO11c/Salt-Light-Components?type=design&node-id=9298%3A626&mode=design&t=0y7Y90OPUPekqC5Q-1) and [Dark](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/1CPaIVIe1tsgGwrqQtciBd/Salt-Dark-Components?type=design&node-id=6240%3A15&mode=design&t=UoaTbwjoiamQqXvv-1) component branches  
[Progress Figma guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/lUjmJcBNGXKiMQqxrowMA5/Salt-Figma-Component-Guides?type=design&node-id=2331%3A8638&mode=design&t=0KJiiudUiCbnH2vP-1) branch

**Comment by parsakhan21** [comment]
July 31 - docs ready to be converted to MDX (James)

**Comment by bhoppers2008** [comment]
Figma component and guide have been merged to main. Ben to publish.

**Comment by AnniaT** [comment]
Figma is done. Ready for release 

Code updates - PR is to be reviewed  - will be ready to release today

**Comment by james-nash** [comment]
FYI: PR for converting docs from Word to MDX is here: https://github.com/jpmorganchase/salt-ds/pull/2109

**Comment by bhoppers2008** [comment]
Figma component and guide published internally and externally.
