### ISSUE TITLE
Update the padding in Accordion's panel

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3944]
## Description

Update Accordion's panel padding to spacing-100 on top and spacing-150 on the bottom.

```[tasklist]
### Tasks
- [ ] Update the Spec
- [ ] Update the Salt (current) Figma library
- [ ] Update the Salt (next) Figma library
- [ ] Update the code
```
