### ISSUE TITLE
Figma Review & Release in Cortado

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3945]
```[tasklist]
### Salt Light/Dark
- [x] ComboBox https://github.com/jpmorganchase/salt-ds/issues/3643 (Yun)
- [x] #3930 Pill update to add menu button following Salt Next (Yun)
- [x] https://github.com/jpmorganchase/salt-ds/issues/3787 (Merged, waiting for the code to be done and publish) Dot Badge: Added Dot Badge variant and component guide to Badge (Yun)
```

```[tasklist]
### Salt Next
- [x] ComboBox https://github.com/jpmorganchase/salt-ds/issues/3643  (Yun)
- [x] Update Stepped Tracker — update characteristics, add vertical nested construction (Ivan)
- [x] https://github.com/jpmorganchase/salt-ds/issues/3787 (Merged, waiting for the code to be done and publish) Dot Badge: Added Dot Badge variant and component guide to Badge (Yun)
- [x] Update Date Picker - Add bordered option to date picker #3796 (Ivan)
```

**Comment by origami-z** [comment]
Aug 12 - list to be updated

**Comment by yunjungyeh** [comment]
Stepped tracker was blocked by Figma merge issue. 
@ivan-calderon created/worked on another branch and @yunjungyeh reviewed and merged on Wed 21 Aug

**Comment by bhoppers2008** [comment]
Released on 23rd September. [Full release notes](https://confluence.prod.aws.jpmchase.net/confluence/display/SALTDS/Figma+release+notes).
