### ISSUE TITLE
JSON representation for theme

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4041]
Catch all issue

```[tasklist]
### Tasks
- [ ] Create JSON representation 
- [ ] Generate CSS to replace most of existing theme package content
- [ ] Publish JSON as part of npm release
- [ ] Write documentation how to integrate with 3rd party libraries (e.g. vanilla-extract for Mosaic, theme visualization)
- [ ] Lint tool to check against Figma library (variables)
```

Some considerations 
- Theme vs Theme next
- Potential different folder / file structure ?
- Handle deprecation
- Token naming difference between Figma and CSS

Prototype in #3143

**Comment by mark-tate** [comment]
Latte Goal: review current state, kickoff to understand requirements at EOS

**Comment by origami-z** [comment]
Oct 17: start in w2, after ag grid work

**Comment by origami-z** [comment]
Oct 21: scheduled a scope meeting on 28 Oct, start looking at dependencies / feasibility this week (e.g. styled dictionary v4 release)

**Comment by mark-tate** [comment]
Lungo Goal: 
document what the JSON representation will NOT do

**Comment by origami-z** [comment]
Met w/ @mark-tate @joshwooding @pseys @dplsek John on Monday

Primary goal for the JSON exercise is for safety and quality control, which would lay the foundation for further expansion for other BYOT requirements
-	For Salt, we can check between synchronization Figma and Code. e.g., See “Would have avoided” in GH issue description above. 
    - We don't want to change existing process (e.g., editing Figma variables via Figma UI, Figma only variables) until risk and new process of syncing between Figma/Code can be fully understood. So the first step would be creating some "lint" tool to warn the user if anything is different is detected, e.g., as a Figma plugin, custom CSS stylelint
    - We should be able to produce CSS code via JSON, instead of manually construct them like now 
    - Further usage could include theme configuration or virtualization tools (e.g., [prototype using spectrum tokens](https://origami-z.github.io/salt-ds-tokens/?filter=light%2Cmedium&remoteJsonUrl=https%253A%252F%252Fraw.githubusercontent.com%252Fjpmorganchase%252Fsalt-ds%252Fcae97dfe8b05fb91baef578f8ca04b25315fdc5e%252Fpackages%252Ftheme%252Fjson%252Ftheme.json&token=palette%2Cneutral))
-	For consumers, they can use the file to check their Salt [“theming”]( https://www.saltdesignsystem.com/salt/themes/index#customizing-with-salt-next) compliance (with our documentation)
    - One example would be providing CSS linting to consumer's code, e.g., Saslt CSS token validation, deprecation 
    - In Figma, this can be used to create / check custom Figma library

This does NOT cover

- Any customization beyond `@salt-ds/theme` package, e.g., component level overrides. 
- Change Salt existing workflow, e.g., how variables are added to Figma

**Comment by origami-z** [comment]
Done some experiments on [4041-json-theme](https://github.com/jpmorganchase/salt-ds/tree/4041-json-theme) using style dictionary v4, with DTCG format. A few findings

- Extracted JSON from Figma variables using [Export styles plugin](https://github.com/jpmorganchase/Figma-Plugins-and-Widgets/tree/main/packages/export-styles)
 - Trying to keep some structure, e.g. alpha tree of color, which needs custom name transformer `salt-ds/name/kebab` to handle
 - Tried with loading multiple source token files from different modes
     -  If loading each mode separately, there is no way to output different modes in the same file like we do today https://github.com/jpmorganchase/salt-ds/blob/dc5b3b36a3225bab4b3e0290202bbac65aacb4ad/packages/theme/css/palette/accent-next.css#L1 https://github.com/jpmorganchase/salt-ds/blob/dc5b3b36a3225bab4b3e0290202bbac65aacb4ad/packages/theme/css/palette/accent-next.css#L17
     - If loading all tokens from different modes, style dictionary will complain token conflicts and only output 1 mode, even if we can write custom formatter to append to the same file, like how [`rule` in "css-advanced" custom format](https://github.com/lukasoppermann/style-dictionary-utils/tree/main?tab=readme-ov-file#cssadvanced)
     - The next approach would be using proposed `$mode` block, then write custom formatter to read value from `$value` (or swapped with different `$mode` value), then output to the same file. This requires a rewrite from style dictionary's `formattedVariables` function, which handles naming / output reference, as well as additional options to be passed down to the function (or formatter)

**Comment by origami-z** [comment]
Spent some time debug internal StyleDictionary code, a few possibilities

1. to use a custom version of `formattedVariables` (from `"style-dictionary/utils"`), so some `$mode` can be used instead of `$value` when resolving reference
    https://github.com/amzn/style-dictionary/blob/ef7b2f6cea9e820fd50c9c34ba7e2f3898b102af/lib/common/formatHelpers/createPropertyFormatter.js#L167
2. continue using `formattedVariables` but alter `dictionary.tokens` so that `$value` block is replaced with `$mode`. This is preferred over above, given we can continue using majority of SD code. There is still some risk around this, given we're relying on knowing how SD internal functionary work
3. Looks like the new [preprocessors](https://styledictionary.com/reference/hooks/preprocessors/) could also work for similar purpose

Continue investigating...

**Comment by origami-z** [comment]
Nov 29 - Make more progress in #4443, with the plan to replace next theme CSS to build from token files.

Found a couple of discrepancies between existing CSS and Figma variables, which needs to be fixed along the way.

**Comment by origami-z** [comment]
Dec 12 - Final update before my leave

I don't want to rush anything in from the work #4443, which contains how tokens are extracted, list of discussions need to be addressed.

**Comment by joshwooding** [comment]
Moved to backlog for now, start sprint was Latte, end was Nokia
