### ISSUE TITLE
Color foundation page

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4047]
```[tasklist]
### Tasks
- [x] Outline new documentation for Legacy + Next
- [x] Update external site Color docs with new content (Button release)
- [ ] https://github.com/jpmorganchase/salt-ds/issues/4230
```

Espresso Goal: Update the website with Status + Sentiment information. Consensus on Color (Legacy + Next) documentation for Color in Foundations

**Comment by amritadesmet** [comment]
Espresso Achievement ✅ : Current site Color pg updated with new Status + Sentiment definitions 

Frappe goal 🎯: Outline the content requirements for the Color pg (what UI could look like + written content)

*Not designing the token ramp UI, coming up with ideas for information layout

**Comment by mark-tate** [comment]
Galao Goal: design hi-fi page for color foundation page using Honey's template

**Comment by joshwooding** [comment]
@amritadesmet can you update this please.

**Comment by amritadesmet** [comment]
Updated content was published
