### ISSUE TITLE
Typography foundation page

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#4057]
The page is currently missing text styles, which will need to be added (#2124)

```[tasklist]
### Tasks
- [x] Outline new documentation for Legacy + Next
- [ ] https://github.com/jpmorganchase/salt-ds/issues/4228
- [ ] Lo-fi mockups for page
```

**Comment by amritadesmet** [comment]
- Outline written content for Legacy + Next
- Align with leads on included content + definitions 
- Lo-fi mockups for page 


Espresso Goal: Outline written content for Legacy + Next, align with leads on documentation information

**Comment by mark-tate** [comment]
Frappe Goal: Content reviewed by Darrin/Paul

**Comment by amritadesmet** [comment]
**Tues 24 Sep:** Content was reviewed by Paul + Darrin in a hands-on working session

**Next step** 🎯: Implement content documentation feedback - to be completed by EOS

**Comment by mark-tate** [comment]
Galao Goal: Update external site Typography docs with new content

**Comment by joshwooding** [comment]
@amritadesmet can you update this please.

**Comment by amritadesmet** [comment]
Updated content was published
