### ISSUE TITLE
Figma Review & Release in Galao + Newsletter

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#4185]
Highlights (suggested)
- Upcoming change of (emoji) use in library props
- Data Viz color palette blog
- TBC
```[tasklist]
### Light/Dark
- [x] Card #3875
- [x] (merged but hidden) Static List #4127
- [x] MIXED - Updates to button references in Figma library documentation to match extended button sets (Data Grid, Segmented Button, Toast, Split Button, Dialog). #3903
- [x] Stepper input #1855
- [x] Contact Details #3853
- [x] Pill #3943
- [x] Banner #3935
- [x] Toggle Button #3903
```

```[tasklist]
### Next
- [x] Meta data in both Next and Icon library #4094
- [x] Card #3875
- [x] Calendar & Date Picker: Addressing Figma regression issues to recover the August 06, 2024 updates
- [x] MIXED - Updates to button references in Figma library documentation to match extended button sets (Overlay, Segmented Button, Form Field, Toast). #3903
- [x] Stepper input #1855
- [x] Contact Details #3853
- [x] Pill #3943
- [x] Accordion - update from open state to expanded boolean
- [ ] File upload pattern #3998
```

```[tasklist]
### Icon Library
- [x] Meta data in both Next and Icon library #4094
- [x] Success Icon Update, Warning & Info #4100
```

```[tasklist]
### Salt (Next) Style Library
- [x] overlayable-background-highlight added to support AG Grid functionality #4115
- [ ] #4113
- [ ] #3876
```

```[tasklist]
### Newsletter Hightlights
- [x] Color blog by Darrin
- [x] Typography foundation updates by Amrita
```

**Comment by yunjungyeh** [comment]
Fri 27 Sep - Reviewed and Merged Pill contact details
Mon 30 Sep - Reviewed and Merged Pill
Fri 4 Oct - Reviewed and Merged Stepper input

**Comment by yunjungyeh** [comment]
Tue 8 Oct - reviewed and merged Static List in Light/Dark @ivan-calderon

**Comment by mark-tate** [comment]
@pseys requires card changes to unblock release (likely 15/10/2024)

**Comment by yunjungyeh** [comment]
Figma parts are ready, waiting for highlights being published on the internal site

**Comment by dplsek** [comment]
extend into Lungo pending an update from @yunjungyeh

**Comment by mark-tate** [comment]
Lungo Goal: Add Q3 deck links and publish

**Comment by yunjungyeh** [comment]
Sent on Tue
