### ISSUE TITLE
Global Brand Presentation contribution

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#4309]
To complete this issue:

```[tasklist]
### Tasks
- [x] Salt's slide contribution to the deck is complete and reviewed
- [x] Dry run is complete
- [ ] Presentation is done
```

**Comment by bhoppers2008** [comment]
Done. Closed.
