### ISSUE TITLE
Business Library Manager forum is set up

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#4310]
To complete this issue:

```[tasklist]
### Tasks
- [x] Business Library Managers and CIB design leads are invited to initial forum on Monday Oct 21st
- [x] 1:1 scheduled with unavailable attendees
- [x] Forum walks BLMs through agreed ui and theme strategy
- [x] BLM distribution list is created (for BLMs and CIB leads)
- [x] Summary email is sent to distribution list.
```
