### ISSUE TITLE
 Figma Review and Release in Red Eye

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#4480]
```[tasklist]
### Light/Dark
- [ ] (waiting for code to release in Figma) Header Block #3839
- [ ] (waiting for code to release in Figma) Dialog #4172 & #4377
- [x] (waiting for code to release in Figma) Button Bar pattern #4174
- [x] (merged, waiting for code to release in Figma) Tabs -> It's planned to be released in Code
- [x] Card naming updates #4395
- [ ] Skip link pattern
- [ ] (Design finish time tbd)Date Picker -> It's planned to be released in Code
- [ ] Component Naming update #4394
- [ ] Stepped Tracker
```

```[tasklist]
### Next
- [ ] (waiting for code to release in Figma) Header Block #3839
- [x] (waiting for code to release in Figma) Dialog #4172 & #4377
- [x] (waiting for code to release in Figma)  Button Bar pattern #4174
- [x] (merged, waiting for code to release in Figma) Tabs -> It's planned to be released in Code
- [ ] Skip link pattern
- [ ] (Design finish time tbd) Date Picker -> It's planned to be released in Code
- [x] Stepped Tracker
- [ ] File Upload Pattern
```

```[tasklist]
### Newsletter Hightlights


```

**Comment by yunjungyeh** [comment]
Released in 20 Dec
