### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#474]
- [x] Density and size – update Characteristics Figma doc and update affected Component specs in Figma
- [x] Figma color palettes – update and publish style libraries for light and dark modes
- [x] Figma typography styles – create and publish typographic styles (inc. Display styles and updated sizes)
- [x] Characteristics – @bhoppers2008 and @pseys to address all open comments assigned to him in Figma
- [x] Storybook documentation for Foundations

## Out of scope

- Explaining low-level characteristic usage to consumers

**Comment by parsakhan21** [comment]
Dev side - not so much work. Need size/characteristics need to be completed. 
Liberty/Zarko looking into documentation.

**Comment by parsakhan21** [comment]
10/21 - Re: documentation - Sion conducting review right now, and will feed back to Liberty/Zarko - by Monday.

**Comment by parsakhan21** [comment]
10/25 - Sion plans to finish content review today.

**Comment by pseys** [comment]
Following discussion with @bhoppers2008 the following is outstanding, from a design perspective, which I'm currently working through:

1. Density and size – update Characteristics Figma doc
2. Density and size – update affected Component specs in Figma
3. Figma color palettes – update and publish style libraries for light and dark modes
4. Figma typography styles – create and publish typographic styles (inc. Display styles and updated sizes)
5. Characteristics – @bhoppers2008 to address all open comments assigned to him in Figma
6. Characteristics – @pseys  to address all open comments assigned to him in Figma
7. Storybook documentation for Foundations

**Comment by parsakhan21** [comment]
10/27 - theme doc review is complete.

**Comment by james-nash** [comment]
11/24: Integrating datagrid characteristics has become a bit of 'mare. Cleaning up docs. Hoping to get them down by the end of the week.
