### ISSUE TITLE
Parent Child Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#480]
```[tasklist]
### Tasks
- [ ] Review API - disableAnimations, stackedViewElement
- [ ] Move to core
- [ ] Review orientation support
- [ ] How to handle accessibility e.g. hidden elements
```
