### ISSUE TITLE
Split Layout

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#481]
```[tasklist]
### Split Layout tasks
- [x] Design spec provided
- [x] Design docs provided
- [x] https://github.com/jpmorganchase/salt-ds/issues/1127
- [x] Dev review
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1128
- [x] Design review
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1129
```

**Comment by Fercas123** [comment]
@maj-stella please see the below link for the split stories:
default: https://layout-examples-ada-update.uitk.pages.dev/?path=/story/core-layout-splitlayout--default-split-layout
simple usage: https://layout-examples-ada-update.uitk.pages.dev/?path=/story/core-layout-splitlayout--split-layout-simple-usage

**Comment by Fercas123** [comment]
@maj-stella please see the fixes you suggested implemented in the default example here: 
https://layout-examples-ada-update.uitk.pages.dev/iframe?id=core-layout-splitlayout--default-split-layout

**Comment by maj-stella** [comment]
Examples reflow correctly. Signed off.

**Comment by parsakhan21** [comment]
1/25 - pr open - need reviews
