### ISSUE TITLE
Pill v1

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#488]
```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] State (Default, Hover, Selected/Active, Disabled, Read-only(Static?), Other)
- [x] Controlled API
- [x] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [x] Optional Clickable pill
- [x] Optional icon descriptor
```

**Comment by yunjungyeh** [comment]
Discussions with @bhoppers2008 @ZarkoPernar  
- should have Read-only(Static) state, maybe in v2
- Fill (Primary, Secondary, Tertiary) can be removed
- Icon usage of pill on left hand side for now, revisit after more understanding about MCP right icon usage
- Can do Closable and Clickable at the same time
- Color-tagging should make sure the colours selected are following ADA


@ZarkoPernar feel free to update/add anything important I miss! Thanks

**Comment by yunjungyeh** [comment]
🟠7 July - Review Shannon’s files
🟠7 July - Review Nav’s Research
🟠5/6 July - Research: reach out to the team to discuss Pill usage (Nav’s research / Transact Larry/ Payments: Mike & James & Jonathan & Felipe / Security Service: Shannon &Thao)
✅5/6 July - Talk to Rich S explore Pill Usage and how do they (MCP) use Pill, understand if there are more interaction usage

✅5 July -  Pill Design Catch up with Ben & Zarko ask questions and tell them I’m going to do research and update characteristics from UITK to Salt
✅ 4 July - Kick off call
✅ 3/4 July - UITK Pill research & Questions for component kickoff

**Comment by dplsek** [comment]
07/07 - Zarko opened pr today, can someone please review?

**Comment by joshwooding** [comment]
Moved to Amber due to the Pill vs Badge conversation

**Comment by parsakhan21** [comment]
July 14 - designs - characteristics specs reviewed with zarko/ben - feedback to be addressed; 
pill/badge mtg next tuesday
dev - changes being made per designs 
docs may be affected based on convo next week

**Comment by ZarkoPernar** [comment]
July 18 - Moving closable to V2

**Comment by yunjungyeh** [comment]
@jpmorganchase/salt-content Please review the Pill Component doc @ZarkoPernar and I have completed in the folder Component Docs, thank you!

**Comment by bhoppers2008** [comment]
Have reviewed the figma artefacts. Some small changes before merging.

**Comment by joshwooding** [comment]
21/07 - Merged into labs and ready to be released today

Will look at plan to move to core

**Comment by parsakhan21** [comment]
July 31 - docs ready to be converted to MDX (James)
