### ISSUE TITLE
Component pages

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#562]
This is an "epic" to plan and track all the work to integrate component pages into our website.

### Tasks

```[tasklist]
### Tasks
- [x] Research how other DS sites present component documentation
- [x] Review past UITK research and feedback on component documentation
- [ ] https://github.com/jpmorganchase/salt-ds/issues/990
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1085
- [x] Explore component page layout designs
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1175
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1150
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1507
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1533
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1573
- [x] Build component page layout
- [x] Build code block component
- [x] Build component preview component (name TBC!)
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1623
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1655
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1665
- [x] Build props table component (?)
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1696
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1044
- [ ] Build enhanced TOC component
```

### Rationale
Instead of linking to Storybook for component pages - as we decided to do for our initial site launch (#519) - we need to incorporate that content and functionality directly into our site. Linking out to Storybook is a jarring experience for users since it has a completely different look and feel to our website.

Note: Storybook will continue to exist and be used, but would be primarily a tool for the DS team to use rather than the place we direct consumers to. To use [Brad Frost's analogy](https://bradfrost.com/blog/post/the-workshop-and-the-storefront/), Storybook would be part of our "workshop" and this issue is about creating the "storefront" version of our component pages.

**Comment by james-nash** [comment]
Given that we have a fully functional component page template (which we've been busy populating with content for all of our components), this issue can be considered done. Therefore closing it now.
