### ISSUE TITLE
Stack Layout direction (Inline)

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#949]
```[tasklist]
### Tasks
- [x] Component implemented in TypeScript
- [x] Functional test script is implemented in Cypress and passes
- [x] All examples needed are implemented as stories (either ported from BitBucket or created net new)
- [x] Design docs provided
- [x] Dev docs content provided
- [x] Consolidated documentation published on Storybook
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1125
- [x] Design review
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1126
```

**Comment by parsakhan21** [comment]
1/18 - in progress
